// _WIN32 で確認しているけど、実際は __WINNT に限定される

#include <windef.h>
#include <windows.h>
//#define RC_INVOKED 1
#define PEXECUTION_STATE NTIFS_H_PEXECUTION_STATE // ntifs.h で再定義するため
#include <ddk/ntifs.h>
#include <ddk/ntstatus.h>
#include <wchar.h>

static inline int ntstatus_to_errno(NTSTATUS s);
static inline const char *ntstatus_to_str(NTSTATUS s);

static inline int
ntstatus_to_errno(NTSTATUS s)
{
  // RtlNtStatusToDosError() を使うべきか？
  // https://learn.microsoft.com/ja-jp/windows/desktop/api/Winternl/nf-winternl-rtlntstatustodoserror

  switch (s) {
  case STATUS_BUFFER_OVERFLOW:          return EINVAL;  // ERANGE? (EOVERFLOW は MinGW で定義されない)
  case STATUS_BUFFER_TOO_SMALL:         return EINVAL;  // ERANGE? (EOVERFLOW は MinGW で定義されない)
  case STATUS_INVALID_INFO_CLASS:       return EINVAL;
  case STATUS_INVALID_PARAMETER:        return EINVAL;
  case STATUS_INVALID_HANDLE:           return EBADF;
  case STATUS_HANDLE_NOT_CLOSABLE:      return EBADF;
  case STATUS_OBJECT_NAME_INVALID:      return EINVAL;
  case STATUS_OBJECT_NAME_NOT_FOUND:    return ENOENT;
  case STATUS_OBJECT_NAME_COLLISION:    return EINVAL;
  case STATUS_OBJECT_PATH_INVALID:      return EINVAL;
  case STATUS_OBJECT_PATH_NOT_FOUND:    return ENOENT;
  case STATUS_OBJECT_PATH_SYNTAX_BAD:   return EINVAL;
  case STATUS_NOT_A_DIRECTORY:          return ENOTDIR;
  case STATUS_ACCESS_DENIED:            return EACCES;
  case STATUS_NO_MORE_FILES:            return ENOENT;  // ?
  }

  if (IS_ERROR(s)) {
    static int print_contact_me = 0;
    LOGF("unified error status to einval (NTSTATUS=0x%08X %s)", (unsigned)s, ntstatus_to_str(s));
    if (!print_contact_me) {
      LOGS("### for improvements, please report to the https://github.com/dearblue/mruby-find/issues ###");
      print_contact_me = 1;
    }
  }

  return IS_ERROR(s) ? EINVAL : 0;
}

// 定義名は /usr/local/mingw32/include/ddk/ntstatus.h から抽出

static inline const char *
ntstatus_to_str(NTSTATUS s)
{
  switch (s) {
  case STATUS_SUCCESS:                                          return "STATUS_SUCCESS";
  //case STATUS_SEVERITY_SUCCESS:                                 return "STATUS_SEVERITY_SUCCESS";
  case STATUS_SEVERITY_INFORMATIONAL:                           return "STATUS_SEVERITY_INFORMATIONAL";
  case STATUS_SEVERITY_WARNING:                                 return "STATUS_SEVERITY_WARNING";
  case STATUS_SEVERITY_ERROR:                                   return "STATUS_SEVERITY_ERROR";
  //case STATUS_WAIT_0:                                           return "STATUS_WAIT_0";
  //case STATUS_WAIT_1:                                           return "STATUS_WAIT_1";
  //case STATUS_WAIT_2:                                           return "STATUS_WAIT_2";
  //case STATUS_WAIT_3:                                           return "STATUS_WAIT_3";
  //case STATUS_WAIT_63:                                          return "STATUS_WAIT_63";
  case STATUS_ABANDONED:                                        return "STATUS_ABANDONED";
  //case STATUS_ABANDONED_WAIT_0:                                 return "STATUS_ABANDONED_WAIT_0";
  //case STATUS_ABANDONED_WAIT_63:                                return "STATUS_ABANDONED_WAIT_63";
  case STATUS_USER_APC:                                         return "STATUS_USER_APC";
  case STATUS_KERNEL_APC:                                       return "STATUS_KERNEL_APC";
  case STATUS_ALERTED:                                          return "STATUS_ALERTED";
  case STATUS_TIMEOUT:                                          return "STATUS_TIMEOUT";
  case STATUS_PENDING:                                          return "STATUS_PENDING";
  case STATUS_REPARSE:                                          return "STATUS_REPARSE";
  case STATUS_MORE_ENTRIES:                                     return "STATUS_MORE_ENTRIES";
  case STATUS_NOT_ALL_ASSIGNED:                                 return "STATUS_NOT_ALL_ASSIGNED";
  case STATUS_SOME_NOT_MAPPED:                                  return "STATUS_SOME_NOT_MAPPED";
  case STATUS_OPLOCK_BREAK_IN_PROGRESS:                         return "STATUS_OPLOCK_BREAK_IN_PROGRESS";
  case STATUS_VOLUME_MOUNTED:                                   return "STATUS_VOLUME_MOUNTED";
  case STATUS_RXACT_COMMITTED:                                  return "STATUS_RXACT_COMMITTED";
  case STATUS_NOTIFY_CLEANUP:                                   return "STATUS_NOTIFY_CLEANUP";
  case STATUS_NOTIFY_ENUM_DIR:                                  return "STATUS_NOTIFY_ENUM_DIR";
  case STATUS_NO_QUOTAS_FOR_ACCOUNT:                            return "STATUS_NO_QUOTAS_FOR_ACCOUNT";
  case STATUS_PRIMARY_TRANSPORT_CONNECT_FAILED:                 return "STATUS_PRIMARY_TRANSPORT_CONNECT_FAILED";
  case STATUS_PAGE_FAULT_TRANSITION:                            return "STATUS_PAGE_FAULT_TRANSITION";
  case STATUS_PAGE_FAULT_DEMAND_ZERO:                           return "STATUS_PAGE_FAULT_DEMAND_ZERO";
  case STATUS_PAGE_FAULT_COPY_ON_WRITE:                         return "STATUS_PAGE_FAULT_COPY_ON_WRITE";
  case STATUS_PAGE_FAULT_GUARD_PAGE:                            return "STATUS_PAGE_FAULT_GUARD_PAGE";
  case STATUS_PAGE_FAULT_PAGING_FILE:                           return "STATUS_PAGE_FAULT_PAGING_FILE";
  case STATUS_CACHE_PAGE_LOCKED:                                return "STATUS_CACHE_PAGE_LOCKED";
  case STATUS_CRASH_DUMP:                                       return "STATUS_CRASH_DUMP";
  case STATUS_BUFFER_ALL_ZEROS:                                 return "STATUS_BUFFER_ALL_ZEROS";
  case STATUS_REPARSE_OBJECT:                                   return "STATUS_REPARSE_OBJECT";
  case STATUS_RESOURCE_REQUIREMENTS_CHANGED:                    return "STATUS_RESOURCE_REQUIREMENTS_CHANGED";
  case STATUS_TRANSLATION_COMPLETE:                             return "STATUS_TRANSLATION_COMPLETE";
  case STATUS_DS_MEMBERSHIP_EVALUATED_LOCALLY:                  return "STATUS_DS_MEMBERSHIP_EVALUATED_LOCALLY";
  case STATUS_NOTHING_TO_TERMINATE:                             return "STATUS_NOTHING_TO_TERMINATE";
  case STATUS_PROCESS_NOT_IN_JOB:                               return "STATUS_PROCESS_NOT_IN_JOB";
  case STATUS_PROCESS_IN_JOB:                                   return "STATUS_PROCESS_IN_JOB";
  case STATUS_OBJECT_NAME_EXISTS:                               return "STATUS_OBJECT_NAME_EXISTS";
  case STATUS_THREAD_WAS_SUSPENDED:                             return "STATUS_THREAD_WAS_SUSPENDED";
  case STATUS_WORKING_SET_LIMIT_RANGE:                          return "STATUS_WORKING_SET_LIMIT_RANGE";
  case STATUS_IMAGE_NOT_AT_BASE:                                return "STATUS_IMAGE_NOT_AT_BASE";
  case STATUS_RXACT_STATE_CREATED:                              return "STATUS_RXACT_STATE_CREATED";
  case STATUS_SEGMENT_NOTIFICATION:                             return "STATUS_SEGMENT_NOTIFICATION";
  case STATUS_LOCAL_USER_SESSION_KEY:                           return "STATUS_LOCAL_USER_SESSION_KEY";
  case STATUS_BAD_CURRENT_DIRECTORY:                            return "STATUS_BAD_CURRENT_DIRECTORY";
  case STATUS_SERIAL_MORE_WRITES:                               return "STATUS_SERIAL_MORE_WRITES";
  case STATUS_REGISTRY_RECOVERED:                               return "STATUS_REGISTRY_RECOVERED";
  case STATUS_FT_READ_RECOVERY_FROM_BACKUP:                     return "STATUS_FT_READ_RECOVERY_FROM_BACKUP";
  case STATUS_FT_WRITE_RECOVERY:                                return "STATUS_FT_WRITE_RECOVERY";
  case STATUS_SERIAL_COUNTER_TIMEOUT:                           return "STATUS_SERIAL_COUNTER_TIMEOUT";
  case STATUS_NULL_LM_PASSWORD:                                 return "STATUS_NULL_LM_PASSWORD";
  case STATUS_IMAGE_MACHINE_TYPE_MISMATCH:                      return "STATUS_IMAGE_MACHINE_TYPE_MISMATCH";
  case STATUS_RECEIVE_PARTIAL:                                  return "STATUS_RECEIVE_PARTIAL";
  case STATUS_RECEIVE_EXPEDITED:                                return "STATUS_RECEIVE_EXPEDITED";
  case STATUS_RECEIVE_PARTIAL_EXPEDITED:                        return "STATUS_RECEIVE_PARTIAL_EXPEDITED";
  case STATUS_EVENT_DONE:                                       return "STATUS_EVENT_DONE";
  case STATUS_EVENT_PENDING:                                    return "STATUS_EVENT_PENDING";
  case STATUS_CHECKING_FILE_SYSTEM:                             return "STATUS_CHECKING_FILE_SYSTEM";
  case STATUS_FATAL_APP_EXIT:                                   return "STATUS_FATAL_APP_EXIT";
  case STATUS_PREDEFINED_HANDLE:                                return "STATUS_PREDEFINED_HANDLE";
  case STATUS_WAS_UNLOCKED:                                     return "STATUS_WAS_UNLOCKED";
  case STATUS_SERVICE_NOTIFICATION:                             return "STATUS_SERVICE_NOTIFICATION";
  case STATUS_WAS_LOCKED:                                       return "STATUS_WAS_LOCKED";
  case STATUS_LOG_HARD_ERROR:                                   return "STATUS_LOG_HARD_ERROR";
  case STATUS_ALREADY_WIN32:                                    return "STATUS_ALREADY_WIN32";
  case STATUS_WX86_UNSIMULATE:                                  return "STATUS_WX86_UNSIMULATE";
  case STATUS_WX86_CONTINUE:                                    return "STATUS_WX86_CONTINUE";
  case STATUS_WX86_SINGLE_STEP:                                 return "STATUS_WX86_SINGLE_STEP";
  case STATUS_WX86_BREAKPOINT:                                  return "STATUS_WX86_BREAKPOINT";
  case STATUS_WX86_EXCEPTION_CONTINUE:                          return "STATUS_WX86_EXCEPTION_CONTINUE";
  case STATUS_WX86_EXCEPTION_LASTCHANCE:                        return "STATUS_WX86_EXCEPTION_LASTCHANCE";
  case STATUS_WX86_EXCEPTION_CHAIN:                             return "STATUS_WX86_EXCEPTION_CHAIN";
  case STATUS_IMAGE_MACHINE_TYPE_MISMATCH_EXE:                  return "STATUS_IMAGE_MACHINE_TYPE_MISMATCH_EXE";
  case STATUS_NO_YIELD_PERFORMED:                               return "STATUS_NO_YIELD_PERFORMED";
  case STATUS_TIMER_RESUME_IGNORED:                             return "STATUS_TIMER_RESUME_IGNORED";
  case STATUS_ARBITRATION_UNHANDLED:                            return "STATUS_ARBITRATION_UNHANDLED";
  case STATUS_CARDBUS_NOT_SUPPORTED:                            return "STATUS_CARDBUS_NOT_SUPPORTED";
  case STATUS_WX86_CREATEWX86TIB:                               return "STATUS_WX86_CREATEWX86TIB";
  case STATUS_MP_PROCESSOR_MISMATCH:                            return "STATUS_MP_PROCESSOR_MISMATCH";
  case STATUS_HIBERNATED:                                       return "STATUS_HIBERNATED";
  case STATUS_RESUME_HIBERNATION:                               return "STATUS_RESUME_HIBERNATION";
  case STATUS_GUARD_PAGE_VIOLATION:                             return "STATUS_GUARD_PAGE_VIOLATION";
  case STATUS_DATATYPE_MISALIGNMENT:                            return "STATUS_DATATYPE_MISALIGNMENT";
  case STATUS_BREAKPOINT:                                       return "STATUS_BREAKPOINT";
  case STATUS_SINGLE_STEP:                                      return "STATUS_SINGLE_STEP";
  case STATUS_BUFFER_OVERFLOW:                                  return "STATUS_BUFFER_OVERFLOW";
  case STATUS_NO_MORE_FILES:                                    return "STATUS_NO_MORE_FILES";
  case STATUS_WAKE_SYSTEM_DEBUGGER:                             return "STATUS_WAKE_SYSTEM_DEBUGGER";
  case STATUS_HANDLES_CLOSED:                                   return "STATUS_HANDLES_CLOSED";
  case STATUS_NO_INHERITANCE:                                   return "STATUS_NO_INHERITANCE";
  case STATUS_GUID_SUBSTITUTION_MADE:                           return "STATUS_GUID_SUBSTITUTION_MADE";
  case STATUS_PARTIAL_COPY:                                     return "STATUS_PARTIAL_COPY";
  case STATUS_DEVICE_PAPER_EMPTY:                               return "STATUS_DEVICE_PAPER_EMPTY";
  case STATUS_DEVICE_POWERED_OFF:                               return "STATUS_DEVICE_POWERED_OFF";
  case STATUS_DEVICE_OFF_LINE:                                  return "STATUS_DEVICE_OFF_LINE";
  case STATUS_DEVICE_BUSY:                                      return "STATUS_DEVICE_BUSY";
  case STATUS_NO_MORE_EAS:                                      return "STATUS_NO_MORE_EAS";
  case STATUS_INVALID_EA_NAME:                                  return "STATUS_INVALID_EA_NAME";
  case STATUS_EA_LIST_INCONSISTENT:                             return "STATUS_EA_LIST_INCONSISTENT";
  case STATUS_INVALID_EA_FLAG:                                  return "STATUS_INVALID_EA_FLAG";
  case STATUS_VERIFY_REQUIRED:                                  return "STATUS_VERIFY_REQUIRED";
  case STATUS_EXTRANEOUS_INFORMATION:                           return "STATUS_EXTRANEOUS_INFORMATION";
  case STATUS_RXACT_COMMIT_NECESSARY:                           return "STATUS_RXACT_COMMIT_NECESSARY";
  case STATUS_NO_MORE_ENTRIES:                                  return "STATUS_NO_MORE_ENTRIES";
  case STATUS_FILEMARK_DETECTED:                                return "STATUS_FILEMARK_DETECTED";
  case STATUS_MEDIA_CHANGED:                                    return "STATUS_MEDIA_CHANGED";
  case STATUS_BUS_RESET:                                        return "STATUS_BUS_RESET";
  case STATUS_END_OF_MEDIA:                                     return "STATUS_END_OF_MEDIA";
  case STATUS_BEGINNING_OF_MEDIA:                               return "STATUS_BEGINNING_OF_MEDIA";
  case STATUS_MEDIA_CHECK:                                      return "STATUS_MEDIA_CHECK";
  case STATUS_SETMARK_DETECTED:                                 return "STATUS_SETMARK_DETECTED";
  case STATUS_NO_DATA_DETECTED:                                 return "STATUS_NO_DATA_DETECTED";
  case STATUS_REDIRECTOR_HAS_OPEN_HANDLES:                      return "STATUS_REDIRECTOR_HAS_OPEN_HANDLES";
  case STATUS_SERVER_HAS_OPEN_HANDLES:                          return "STATUS_SERVER_HAS_OPEN_HANDLES";
  case STATUS_ALREADY_DISCONNECTED:                             return "STATUS_ALREADY_DISCONNECTED";
  case STATUS_LONGJUMP:                                         return "STATUS_LONGJUMP";
  case STATUS_CLEANER_CARTRIDGE_INSTALLED:                      return "STATUS_CLEANER_CARTRIDGE_INSTALLED";
  case STATUS_PLUGPLAY_QUERY_VETOED:                            return "STATUS_PLUGPLAY_QUERY_VETOED";
  case STATUS_UNWIND_CONSOLIDATE:                               return "STATUS_UNWIND_CONSOLIDATE";
  case STATUS_CLUSTER_NODE_ALREADY_UP:                          return "STATUS_CLUSTER_NODE_ALREADY_UP";
  case STATUS_CLUSTER_NODE_ALREADY_DOWN:                        return "STATUS_CLUSTER_NODE_ALREADY_DOWN";
  case STATUS_CLUSTER_NETWORK_ALREADY_ONLINE:                   return "STATUS_CLUSTER_NETWORK_ALREADY_ONLINE";
  case STATUS_CLUSTER_NETWORK_ALREADY_OFFLINE:                  return "STATUS_CLUSTER_NETWORK_ALREADY_OFFLINE";
  case STATUS_CLUSTER_NODE_ALREADY_MEMBER:                      return "STATUS_CLUSTER_NODE_ALREADY_MEMBER";
  case STATUS_UNSUCCESSFUL:                                     return "STATUS_UNSUCCESSFUL";
  case STATUS_NOT_IMPLEMENTED:                                  return "STATUS_NOT_IMPLEMENTED";
  case STATUS_INVALID_INFO_CLASS:                               return "STATUS_INVALID_INFO_CLASS";
  case STATUS_INFO_LENGTH_MISMATCH:                             return "STATUS_INFO_LENGTH_MISMATCH";
  case STATUS_ACCESS_VIOLATION:                                 return "STATUS_ACCESS_VIOLATION";
  case STATUS_IN_PAGE_ERROR:                                    return "STATUS_IN_PAGE_ERROR";
  case STATUS_PAGEFILE_QUOTA:                                   return "STATUS_PAGEFILE_QUOTA";
  case STATUS_INVALID_HANDLE:                                   return "STATUS_INVALID_HANDLE";
  case STATUS_BAD_INITIAL_STACK:                                return "STATUS_BAD_INITIAL_STACK";
  case STATUS_BAD_INITIAL_PC:                                   return "STATUS_BAD_INITIAL_PC";
  case STATUS_INVALID_CID:                                      return "STATUS_INVALID_CID";
  case STATUS_TIMER_NOT_CANCELED:                               return "STATUS_TIMER_NOT_CANCELED";
  case STATUS_INVALID_PARAMETER:                                return "STATUS_INVALID_PARAMETER";
  case STATUS_NO_SUCH_DEVICE:                                   return "STATUS_NO_SUCH_DEVICE";
  case STATUS_NO_SUCH_FILE:                                     return "STATUS_NO_SUCH_FILE";
  case STATUS_INVALID_DEVICE_REQUEST:                           return "STATUS_INVALID_DEVICE_REQUEST";
  case STATUS_END_OF_FILE:                                      return "STATUS_END_OF_FILE";
  case STATUS_WRONG_VOLUME:                                     return "STATUS_WRONG_VOLUME";
  case STATUS_NO_MEDIA_IN_DEVICE:                               return "STATUS_NO_MEDIA_IN_DEVICE";
  case STATUS_UNRECOGNIZED_MEDIA:                               return "STATUS_UNRECOGNIZED_MEDIA";
  case STATUS_NONEXISTENT_SECTOR:                               return "STATUS_NONEXISTENT_SECTOR";
  case STATUS_MORE_PROCESSING_REQUIRED:                         return "STATUS_MORE_PROCESSING_REQUIRED";
  case STATUS_NO_MEMORY:                                        return "STATUS_NO_MEMORY";
  case STATUS_CONFLICTING_ADDRESSES:                            return "STATUS_CONFLICTING_ADDRESSES";
  case STATUS_NOT_MAPPED_VIEW:                                  return "STATUS_NOT_MAPPED_VIEW";
  case STATUS_UNABLE_TO_FREE_VM:                                return "STATUS_UNABLE_TO_FREE_VM";
  case STATUS_UNABLE_TO_DELETE_SECTION:                         return "STATUS_UNABLE_TO_DELETE_SECTION";
  case STATUS_INVALID_SYSTEM_SERVICE:                           return "STATUS_INVALID_SYSTEM_SERVICE";
  case STATUS_ILLEGAL_INSTRUCTION:                              return "STATUS_ILLEGAL_INSTRUCTION";
  case STATUS_INVALID_LOCK_SEQUENCE:                            return "STATUS_INVALID_LOCK_SEQUENCE";
  case STATUS_INVALID_VIEW_SIZE:                                return "STATUS_INVALID_VIEW_SIZE";
  case STATUS_INVALID_FILE_FOR_SECTION:                         return "STATUS_INVALID_FILE_FOR_SECTION";
  case STATUS_ALREADY_COMMITTED:                                return "STATUS_ALREADY_COMMITTED";
  case STATUS_ACCESS_DENIED:                                    return "STATUS_ACCESS_DENIED";
  case STATUS_BUFFER_TOO_SMALL:                                 return "STATUS_BUFFER_TOO_SMALL";
  case STATUS_OBJECT_TYPE_MISMATCH:                             return "STATUS_OBJECT_TYPE_MISMATCH";
  case STATUS_NONCONTINUABLE_EXCEPTION:                         return "STATUS_NONCONTINUABLE_EXCEPTION";
  case STATUS_INVALID_DISPOSITION:                              return "STATUS_INVALID_DISPOSITION";
  case STATUS_UNWIND:                                           return "STATUS_UNWIND";
  case STATUS_BAD_STACK:                                        return "STATUS_BAD_STACK";
  case STATUS_INVALID_UNWIND_TARGET:                            return "STATUS_INVALID_UNWIND_TARGET";
  case STATUS_NOT_LOCKED:                                       return "STATUS_NOT_LOCKED";
  case STATUS_PARITY_ERROR:                                     return "STATUS_PARITY_ERROR";
  case STATUS_UNABLE_TO_DECOMMIT_VM:                            return "STATUS_UNABLE_TO_DECOMMIT_VM";
  case STATUS_NOT_COMMITTED:                                    return "STATUS_NOT_COMMITTED";
  case STATUS_INVALID_PORT_ATTRIBUTES:                          return "STATUS_INVALID_PORT_ATTRIBUTES";
  case STATUS_PORT_MESSAGE_TOO_LONG:                            return "STATUS_PORT_MESSAGE_TOO_LONG";
  case STATUS_INVALID_PARAMETER_MIX:                            return "STATUS_INVALID_PARAMETER_MIX";
  case STATUS_INVALID_QUOTA_LOWER:                              return "STATUS_INVALID_QUOTA_LOWER";
  case STATUS_DISK_CORRUPT_ERROR:                               return "STATUS_DISK_CORRUPT_ERROR";
  case STATUS_OBJECT_NAME_INVALID:                              return "STATUS_OBJECT_NAME_INVALID";
  case STATUS_OBJECT_NAME_NOT_FOUND:                            return "STATUS_OBJECT_NAME_NOT_FOUND";
  case STATUS_OBJECT_NAME_COLLISION:                            return "STATUS_OBJECT_NAME_COLLISION";
  case STATUS_PORT_DISCONNECTED:                                return "STATUS_PORT_DISCONNECTED";
  case STATUS_DEVICE_ALREADY_ATTACHED:                          return "STATUS_DEVICE_ALREADY_ATTACHED";
  case STATUS_OBJECT_PATH_INVALID:                              return "STATUS_OBJECT_PATH_INVALID";
  case STATUS_OBJECT_PATH_NOT_FOUND:                            return "STATUS_OBJECT_PATH_NOT_FOUND";
  case STATUS_OBJECT_PATH_SYNTAX_BAD:                           return "STATUS_OBJECT_PATH_SYNTAX_BAD";
  case STATUS_DATA_OVERRUN:                                     return "STATUS_DATA_OVERRUN";
  case STATUS_DATA_LATE_ERROR:                                  return "STATUS_DATA_LATE_ERROR";
  case STATUS_DATA_ERROR:                                       return "STATUS_DATA_ERROR";
  case STATUS_CRC_ERROR:                                        return "STATUS_CRC_ERROR";
  case STATUS_SECTION_TOO_BIG:                                  return "STATUS_SECTION_TOO_BIG";
  case STATUS_PORT_CONNECTION_REFUSED:                          return "STATUS_PORT_CONNECTION_REFUSED";
  case STATUS_INVALID_PORT_HANDLE:                              return "STATUS_INVALID_PORT_HANDLE";
  case STATUS_SHARING_VIOLATION:                                return "STATUS_SHARING_VIOLATION";
  case STATUS_QUOTA_EXCEEDED:                                   return "STATUS_QUOTA_EXCEEDED";
  case STATUS_INVALID_PAGE_PROTECTION:                          return "STATUS_INVALID_PAGE_PROTECTION";
  case STATUS_MUTANT_NOT_OWNED:                                 return "STATUS_MUTANT_NOT_OWNED";
  case STATUS_SEMAPHORE_LIMIT_EXCEEDED:                         return "STATUS_SEMAPHORE_LIMIT_EXCEEDED";
  case STATUS_PORT_ALREADY_SET:                                 return "STATUS_PORT_ALREADY_SET";
  case STATUS_SECTION_NOT_IMAGE:                                return "STATUS_SECTION_NOT_IMAGE";
  case STATUS_SUSPEND_COUNT_EXCEEDED:                           return "STATUS_SUSPEND_COUNT_EXCEEDED";
  case STATUS_THREAD_IS_TERMINATING:                            return "STATUS_THREAD_IS_TERMINATING";
  case STATUS_BAD_WORKING_SET_LIMIT:                            return "STATUS_BAD_WORKING_SET_LIMIT";
  case STATUS_INCOMPATIBLE_FILE_MAP:                            return "STATUS_INCOMPATIBLE_FILE_MAP";
  case STATUS_SECTION_PROTECTION:                               return "STATUS_SECTION_PROTECTION";
  case STATUS_EAS_NOT_SUPPORTED:                                return "STATUS_EAS_NOT_SUPPORTED";
  case STATUS_EA_TOO_LARGE:                                     return "STATUS_EA_TOO_LARGE";
  case STATUS_NONEXISTENT_EA_ENTRY:                             return "STATUS_NONEXISTENT_EA_ENTRY";
  case STATUS_NO_EAS_ON_FILE:                                   return "STATUS_NO_EAS_ON_FILE";
  case STATUS_EA_CORRUPT_ERROR:                                 return "STATUS_EA_CORRUPT_ERROR";
  case STATUS_FILE_LOCK_CONFLICT:                               return "STATUS_FILE_LOCK_CONFLICT";
  case STATUS_LOCK_NOT_GRANTED:                                 return "STATUS_LOCK_NOT_GRANTED";
  case STATUS_DELETE_PENDING:                                   return "STATUS_DELETE_PENDING";
  case STATUS_CTL_FILE_NOT_SUPPORTED:                           return "STATUS_CTL_FILE_NOT_SUPPORTED";
  case STATUS_UNKNOWN_REVISION:                                 return "STATUS_UNKNOWN_REVISION";
  case STATUS_REVISION_MISMATCH:                                return "STATUS_REVISION_MISMATCH";
  case STATUS_INVALID_OWNER:                                    return "STATUS_INVALID_OWNER";
  case STATUS_INVALID_PRIMARY_GROUP:                            return "STATUS_INVALID_PRIMARY_GROUP";
  case STATUS_NO_IMPERSONATION_TOKEN:                           return "STATUS_NO_IMPERSONATION_TOKEN";
  case STATUS_CANT_DISABLE_MANDATORY:                           return "STATUS_CANT_DISABLE_MANDATORY";
  case STATUS_NO_LOGON_SERVERS:                                 return "STATUS_NO_LOGON_SERVERS";
  case STATUS_NO_SUCH_LOGON_SESSION:                            return "STATUS_NO_SUCH_LOGON_SESSION";
  case STATUS_NO_SUCH_PRIVILEGE:                                return "STATUS_NO_SUCH_PRIVILEGE";
  case STATUS_PRIVILEGE_NOT_HELD:                               return "STATUS_PRIVILEGE_NOT_HELD";
  case STATUS_INVALID_ACCOUNT_NAME:                             return "STATUS_INVALID_ACCOUNT_NAME";
  case STATUS_USER_EXISTS:                                      return "STATUS_USER_EXISTS";
  case STATUS_NO_SUCH_USER:                                     return "STATUS_NO_SUCH_USER";
  case STATUS_GROUP_EXISTS:                                     return "STATUS_GROUP_EXISTS";
  case STATUS_NO_SUCH_GROUP:                                    return "STATUS_NO_SUCH_GROUP";
  case STATUS_MEMBER_IN_GROUP:                                  return "STATUS_MEMBER_IN_GROUP";
  case STATUS_MEMBER_NOT_IN_GROUP:                              return "STATUS_MEMBER_NOT_IN_GROUP";
  case STATUS_LAST_ADMIN:                                       return "STATUS_LAST_ADMIN";
  case STATUS_WRONG_PASSWORD:                                   return "STATUS_WRONG_PASSWORD";
  case STATUS_ILL_FORMED_PASSWORD:                              return "STATUS_ILL_FORMED_PASSWORD";
  case STATUS_PASSWORD_RESTRICTION:                             return "STATUS_PASSWORD_RESTRICTION";
  case STATUS_LOGON_FAILURE:                                    return "STATUS_LOGON_FAILURE";
  case STATUS_ACCOUNT_RESTRICTION:                              return "STATUS_ACCOUNT_RESTRICTION";
  case STATUS_INVALID_LOGON_HOURS:                              return "STATUS_INVALID_LOGON_HOURS";
  case STATUS_INVALID_WORKSTATION:                              return "STATUS_INVALID_WORKSTATION";
  case STATUS_PASSWORD_EXPIRED:                                 return "STATUS_PASSWORD_EXPIRED";
  case STATUS_ACCOUNT_DISABLED:                                 return "STATUS_ACCOUNT_DISABLED";
  case STATUS_NONE_MAPPED:                                      return "STATUS_NONE_MAPPED";
  case STATUS_TOO_MANY_LUIDS_REQUESTED:                         return "STATUS_TOO_MANY_LUIDS_REQUESTED";
  case STATUS_LUIDS_EXHAUSTED:                                  return "STATUS_LUIDS_EXHAUSTED";
  case STATUS_INVALID_SUB_AUTHORITY:                            return "STATUS_INVALID_SUB_AUTHORITY";
  case STATUS_INVALID_ACL:                                      return "STATUS_INVALID_ACL";
  case STATUS_INVALID_SID:                                      return "STATUS_INVALID_SID";
  case STATUS_INVALID_SECURITY_DESCR:                           return "STATUS_INVALID_SECURITY_DESCR";
  case STATUS_PROCEDURE_NOT_FOUND:                              return "STATUS_PROCEDURE_NOT_FOUND";
  case STATUS_INVALID_IMAGE_FORMAT:                             return "STATUS_INVALID_IMAGE_FORMAT";
  case STATUS_NO_TOKEN:                                         return "STATUS_NO_TOKEN";
  case STATUS_BAD_INHERITANCE_ACL:                              return "STATUS_BAD_INHERITANCE_ACL";
  case STATUS_RANGE_NOT_LOCKED:                                 return "STATUS_RANGE_NOT_LOCKED";
  case STATUS_DISK_FULL:                                        return "STATUS_DISK_FULL";
  case STATUS_SERVER_DISABLED:                                  return "STATUS_SERVER_DISABLED";
  case STATUS_SERVER_NOT_DISABLED:                              return "STATUS_SERVER_NOT_DISABLED";
  case STATUS_TOO_MANY_GUIDS_REQUESTED:                         return "STATUS_TOO_MANY_GUIDS_REQUESTED";
  case STATUS_GUIDS_EXHAUSTED:                                  return "STATUS_GUIDS_EXHAUSTED";
  case STATUS_INVALID_ID_AUTHORITY:                             return "STATUS_INVALID_ID_AUTHORITY";
  case STATUS_AGENTS_EXHAUSTED:                                 return "STATUS_AGENTS_EXHAUSTED";
  case STATUS_INVALID_VOLUME_LABEL:                             return "STATUS_INVALID_VOLUME_LABEL";
  case STATUS_SECTION_NOT_EXTENDED:                             return "STATUS_SECTION_NOT_EXTENDED";
  case STATUS_NOT_MAPPED_DATA:                                  return "STATUS_NOT_MAPPED_DATA";
  case STATUS_RESOURCE_DATA_NOT_FOUND:                          return "STATUS_RESOURCE_DATA_NOT_FOUND";
  case STATUS_RESOURCE_TYPE_NOT_FOUND:                          return "STATUS_RESOURCE_TYPE_NOT_FOUND";
  case STATUS_RESOURCE_NAME_NOT_FOUND:                          return "STATUS_RESOURCE_NAME_NOT_FOUND";
  case STATUS_ARRAY_BOUNDS_EXCEEDED:                            return "STATUS_ARRAY_BOUNDS_EXCEEDED";
  case STATUS_FLOAT_DENORMAL_OPERAND:                           return "STATUS_FLOAT_DENORMAL_OPERAND";
  case STATUS_FLOAT_DIVIDE_BY_ZERO:                             return "STATUS_FLOAT_DIVIDE_BY_ZERO";
  case STATUS_FLOAT_INEXACT_RESULT:                             return "STATUS_FLOAT_INEXACT_RESULT";
  case STATUS_FLOAT_INVALID_OPERATION:                          return "STATUS_FLOAT_INVALID_OPERATION";
  case STATUS_FLOAT_OVERFLOW:                                   return "STATUS_FLOAT_OVERFLOW";
  case STATUS_FLOAT_STACK_CHECK:                                return "STATUS_FLOAT_STACK_CHECK";
  case STATUS_FLOAT_UNDERFLOW:                                  return "STATUS_FLOAT_UNDERFLOW";
  case STATUS_INTEGER_DIVIDE_BY_ZERO:                           return "STATUS_INTEGER_DIVIDE_BY_ZERO";
  case STATUS_INTEGER_OVERFLOW:                                 return "STATUS_INTEGER_OVERFLOW";
  case STATUS_PRIVILEGED_INSTRUCTION:                           return "STATUS_PRIVILEGED_INSTRUCTION";
  case STATUS_TOO_MANY_PAGING_FILES:                            return "STATUS_TOO_MANY_PAGING_FILES";
  case STATUS_FILE_INVALID:                                     return "STATUS_FILE_INVALID";
  case STATUS_ALLOTTED_SPACE_EXCEEDED:                          return "STATUS_ALLOTTED_SPACE_EXCEEDED";
  case STATUS_INSUFFICIENT_RESOURCES:                           return "STATUS_INSUFFICIENT_RESOURCES";
  case STATUS_DFS_EXIT_PATH_FOUND:                              return "STATUS_DFS_EXIT_PATH_FOUND";
  case STATUS_DEVICE_DATA_ERROR:                                return "STATUS_DEVICE_DATA_ERROR";
  case STATUS_DEVICE_NOT_CONNECTED:                             return "STATUS_DEVICE_NOT_CONNECTED";
  case STATUS_DEVICE_POWER_FAILURE:                             return "STATUS_DEVICE_POWER_FAILURE";
  case STATUS_FREE_VM_NOT_AT_BASE:                              return "STATUS_FREE_VM_NOT_AT_BASE";
  case STATUS_MEMORY_NOT_ALLOCATED:                             return "STATUS_MEMORY_NOT_ALLOCATED";
  case STATUS_WORKING_SET_QUOTA:                                return "STATUS_WORKING_SET_QUOTA";
  case STATUS_MEDIA_WRITE_PROTECTED:                            return "STATUS_MEDIA_WRITE_PROTECTED";
  case STATUS_DEVICE_NOT_READY:                                 return "STATUS_DEVICE_NOT_READY";
  case STATUS_INVALID_GROUP_ATTRIBUTES:                         return "STATUS_INVALID_GROUP_ATTRIBUTES";
  case STATUS_BAD_IMPERSONATION_LEVEL:                          return "STATUS_BAD_IMPERSONATION_LEVEL";
  case STATUS_CANT_OPEN_ANONYMOUS:                              return "STATUS_CANT_OPEN_ANONYMOUS";
  case STATUS_BAD_VALIDATION_CLASS:                             return "STATUS_BAD_VALIDATION_CLASS";
  case STATUS_BAD_TOKEN_TYPE:                                   return "STATUS_BAD_TOKEN_TYPE";
  case STATUS_BAD_MASTER_BOOT_RECORD:                           return "STATUS_BAD_MASTER_BOOT_RECORD";
  case STATUS_INSTRUCTION_MISALIGNMENT:                         return "STATUS_INSTRUCTION_MISALIGNMENT";
  case STATUS_INSTANCE_NOT_AVAILABLE:                           return "STATUS_INSTANCE_NOT_AVAILABLE";
  case STATUS_PIPE_NOT_AVAILABLE:                               return "STATUS_PIPE_NOT_AVAILABLE";
  case STATUS_INVALID_PIPE_STATE:                               return "STATUS_INVALID_PIPE_STATE";
  case STATUS_PIPE_BUSY:                                        return "STATUS_PIPE_BUSY";
  case STATUS_ILLEGAL_FUNCTION:                                 return "STATUS_ILLEGAL_FUNCTION";
  case STATUS_PIPE_DISCONNECTED:                                return "STATUS_PIPE_DISCONNECTED";
  case STATUS_PIPE_CLOSING:                                     return "STATUS_PIPE_CLOSING";
  case STATUS_PIPE_CONNECTED:                                   return "STATUS_PIPE_CONNECTED";
  case STATUS_PIPE_LISTENING:                                   return "STATUS_PIPE_LISTENING";
  case STATUS_INVALID_READ_MODE:                                return "STATUS_INVALID_READ_MODE";
  case STATUS_IO_TIMEOUT:                                       return "STATUS_IO_TIMEOUT";
  case STATUS_FILE_FORCED_CLOSED:                               return "STATUS_FILE_FORCED_CLOSED";
  case STATUS_PROFILING_NOT_STARTED:                            return "STATUS_PROFILING_NOT_STARTED";
  case STATUS_PROFILING_NOT_STOPPED:                            return "STATUS_PROFILING_NOT_STOPPED";
  case STATUS_COULD_NOT_INTERPRET:                              return "STATUS_COULD_NOT_INTERPRET";
  case STATUS_FILE_IS_A_DIRECTORY:                              return "STATUS_FILE_IS_A_DIRECTORY";
  case STATUS_NOT_SUPPORTED:                                    return "STATUS_NOT_SUPPORTED";
  case STATUS_REMOTE_NOT_LISTENING:                             return "STATUS_REMOTE_NOT_LISTENING";
  case STATUS_DUPLICATE_NAME:                                   return "STATUS_DUPLICATE_NAME";
  case STATUS_BAD_NETWORK_PATH:                                 return "STATUS_BAD_NETWORK_PATH";
  case STATUS_NETWORK_BUSY:                                     return "STATUS_NETWORK_BUSY";
  case STATUS_DEVICE_DOES_NOT_EXIST:                            return "STATUS_DEVICE_DOES_NOT_EXIST";
  case STATUS_TOO_MANY_COMMANDS:                                return "STATUS_TOO_MANY_COMMANDS";
  case STATUS_ADAPTER_HARDWARE_ERROR:                           return "STATUS_ADAPTER_HARDWARE_ERROR";
  case STATUS_INVALID_NETWORK_RESPONSE:                         return "STATUS_INVALID_NETWORK_RESPONSE";
  case STATUS_UNEXPECTED_NETWORK_ERROR:                         return "STATUS_UNEXPECTED_NETWORK_ERROR";
  case STATUS_BAD_REMOTE_ADAPTER:                               return "STATUS_BAD_REMOTE_ADAPTER";
  case STATUS_PRINT_QUEUE_FULL:                                 return "STATUS_PRINT_QUEUE_FULL";
  case STATUS_NO_SPOOL_SPACE:                                   return "STATUS_NO_SPOOL_SPACE";
  case STATUS_PRINT_CANCELLED:                                  return "STATUS_PRINT_CANCELLED";
  case STATUS_NETWORK_NAME_DELETED:                             return "STATUS_NETWORK_NAME_DELETED";
  case STATUS_NETWORK_ACCESS_DENIED:                            return "STATUS_NETWORK_ACCESS_DENIED";
  case STATUS_BAD_DEVICE_TYPE:                                  return "STATUS_BAD_DEVICE_TYPE";
  case STATUS_BAD_NETWORK_NAME:                                 return "STATUS_BAD_NETWORK_NAME";
  case STATUS_TOO_MANY_NAMES:                                   return "STATUS_TOO_MANY_NAMES";
  case STATUS_TOO_MANY_SESSIONS:                                return "STATUS_TOO_MANY_SESSIONS";
  case STATUS_SHARING_PAUSED:                                   return "STATUS_SHARING_PAUSED";
  case STATUS_REQUEST_NOT_ACCEPTED:                             return "STATUS_REQUEST_NOT_ACCEPTED";
  case STATUS_REDIRECTOR_PAUSED:                                return "STATUS_REDIRECTOR_PAUSED";
  case STATUS_NET_WRITE_FAULT:                                  return "STATUS_NET_WRITE_FAULT";
  case STATUS_PROFILING_AT_LIMIT:                               return "STATUS_PROFILING_AT_LIMIT";
  case STATUS_NOT_SAME_DEVICE:                                  return "STATUS_NOT_SAME_DEVICE";
  case STATUS_FILE_RENAMED:                                     return "STATUS_FILE_RENAMED";
  case STATUS_VIRTUAL_CIRCUIT_CLOSED:                           return "STATUS_VIRTUAL_CIRCUIT_CLOSED";
  case STATUS_NO_SECURITY_ON_OBJECT:                            return "STATUS_NO_SECURITY_ON_OBJECT";
  case STATUS_CANT_WAIT:                                        return "STATUS_CANT_WAIT";
  case STATUS_PIPE_EMPTY:                                       return "STATUS_PIPE_EMPTY";
  case STATUS_CANT_ACCESS_DOMAIN_INFO:                          return "STATUS_CANT_ACCESS_DOMAIN_INFO";
  case STATUS_CANT_TERMINATE_SELF:                              return "STATUS_CANT_TERMINATE_SELF";
  case STATUS_INVALID_SERVER_STATE:                             return "STATUS_INVALID_SERVER_STATE";
  case STATUS_INVALID_DOMAIN_STATE:                             return "STATUS_INVALID_DOMAIN_STATE";
  case STATUS_INVALID_DOMAIN_ROLE:                              return "STATUS_INVALID_DOMAIN_ROLE";
  case STATUS_NO_SUCH_DOMAIN:                                   return "STATUS_NO_SUCH_DOMAIN";
  case STATUS_DOMAIN_EXISTS:                                    return "STATUS_DOMAIN_EXISTS";
  case STATUS_DOMAIN_LIMIT_EXCEEDED:                            return "STATUS_DOMAIN_LIMIT_EXCEEDED";
  case STATUS_OPLOCK_NOT_GRANTED:                               return "STATUS_OPLOCK_NOT_GRANTED";
  case STATUS_INVALID_OPLOCK_PROTOCOL:                          return "STATUS_INVALID_OPLOCK_PROTOCOL";
  case STATUS_INTERNAL_DB_CORRUPTION:                           return "STATUS_INTERNAL_DB_CORRUPTION";
  case STATUS_INTERNAL_ERROR:                                   return "STATUS_INTERNAL_ERROR";
  case STATUS_GENERIC_NOT_MAPPED:                               return "STATUS_GENERIC_NOT_MAPPED";
  case STATUS_BAD_DESCRIPTOR_FORMAT:                            return "STATUS_BAD_DESCRIPTOR_FORMAT";
  case STATUS_INVALID_USER_BUFFER:                              return "STATUS_INVALID_USER_BUFFER";
  case STATUS_UNEXPECTED_IO_ERROR:                              return "STATUS_UNEXPECTED_IO_ERROR";
  case STATUS_UNEXPECTED_MM_CREATE_ERR:                         return "STATUS_UNEXPECTED_MM_CREATE_ERR";
  case STATUS_UNEXPECTED_MM_MAP_ERROR:                          return "STATUS_UNEXPECTED_MM_MAP_ERROR";
  case STATUS_UNEXPECTED_MM_EXTEND_ERR:                         return "STATUS_UNEXPECTED_MM_EXTEND_ERR";
  case STATUS_NOT_LOGON_PROCESS:                                return "STATUS_NOT_LOGON_PROCESS";
  case STATUS_LOGON_SESSION_EXISTS:                             return "STATUS_LOGON_SESSION_EXISTS";
  case STATUS_INVALID_PARAMETER_1:                              return "STATUS_INVALID_PARAMETER_1";
  case STATUS_INVALID_PARAMETER_2:                              return "STATUS_INVALID_PARAMETER_2";
  case STATUS_INVALID_PARAMETER_3:                              return "STATUS_INVALID_PARAMETER_3";
  case STATUS_INVALID_PARAMETER_4:                              return "STATUS_INVALID_PARAMETER_4";
  case STATUS_INVALID_PARAMETER_5:                              return "STATUS_INVALID_PARAMETER_5";
  case STATUS_INVALID_PARAMETER_6:                              return "STATUS_INVALID_PARAMETER_6";
  case STATUS_INVALID_PARAMETER_7:                              return "STATUS_INVALID_PARAMETER_7";
  case STATUS_INVALID_PARAMETER_8:                              return "STATUS_INVALID_PARAMETER_8";
  case STATUS_INVALID_PARAMETER_9:                              return "STATUS_INVALID_PARAMETER_9";
  case STATUS_INVALID_PARAMETER_10:                             return "STATUS_INVALID_PARAMETER_10";
  case STATUS_INVALID_PARAMETER_11:                             return "STATUS_INVALID_PARAMETER_11";
  case STATUS_INVALID_PARAMETER_12:                             return "STATUS_INVALID_PARAMETER_12";
  case STATUS_REDIRECTOR_NOT_STARTED:                           return "STATUS_REDIRECTOR_NOT_STARTED";
  case STATUS_REDIRECTOR_STARTED:                               return "STATUS_REDIRECTOR_STARTED";
  case STATUS_STACK_OVERFLOW:                                   return "STATUS_STACK_OVERFLOW";
  case STATUS_NO_SUCH_PACKAGE:                                  return "STATUS_NO_SUCH_PACKAGE";
  case STATUS_BAD_FUNCTION_TABLE:                               return "STATUS_BAD_FUNCTION_TABLE";
  case STATUS_VARIABLE_NOT_FOUND:                               return "STATUS_VARIABLE_NOT_FOUND";
  case STATUS_DIRECTORY_NOT_EMPTY:                              return "STATUS_DIRECTORY_NOT_EMPTY";
  case STATUS_FILE_CORRUPT_ERROR:                               return "STATUS_FILE_CORRUPT_ERROR";
  case STATUS_NOT_A_DIRECTORY:                                  return "STATUS_NOT_A_DIRECTORY";
  case STATUS_BAD_LOGON_SESSION_STATE:                          return "STATUS_BAD_LOGON_SESSION_STATE";
  case STATUS_LOGON_SESSION_COLLISION:                          return "STATUS_LOGON_SESSION_COLLISION";
  case STATUS_NAME_TOO_LONG:                                    return "STATUS_NAME_TOO_LONG";
  case STATUS_FILES_OPEN:                                       return "STATUS_FILES_OPEN";
  case STATUS_CONNECTION_IN_USE:                                return "STATUS_CONNECTION_IN_USE";
  case STATUS_MESSAGE_NOT_FOUND:                                return "STATUS_MESSAGE_NOT_FOUND";
  case STATUS_PROCESS_IS_TERMINATING:                           return "STATUS_PROCESS_IS_TERMINATING";
  case STATUS_INVALID_LOGON_TYPE:                               return "STATUS_INVALID_LOGON_TYPE";
  case STATUS_NO_GUID_TRANSLATION:                              return "STATUS_NO_GUID_TRANSLATION";
  case STATUS_CANNOT_IMPERSONATE:                               return "STATUS_CANNOT_IMPERSONATE";
  case STATUS_IMAGE_ALREADY_LOADED:                             return "STATUS_IMAGE_ALREADY_LOADED";
  case STATUS_ABIOS_NOT_PRESENT:                                return "STATUS_ABIOS_NOT_PRESENT";
  case STATUS_ABIOS_LID_NOT_EXIST:                              return "STATUS_ABIOS_LID_NOT_EXIST";
  case STATUS_ABIOS_LID_ALREADY_OWNED:                          return "STATUS_ABIOS_LID_ALREADY_OWNED";
  case STATUS_ABIOS_NOT_LID_OWNER:                              return "STATUS_ABIOS_NOT_LID_OWNER";
  case STATUS_ABIOS_INVALID_COMMAND:                            return "STATUS_ABIOS_INVALID_COMMAND";
  case STATUS_ABIOS_INVALID_LID:                                return "STATUS_ABIOS_INVALID_LID";
  case STATUS_ABIOS_SELECTOR_NOT_AVAILABLE:                     return "STATUS_ABIOS_SELECTOR_NOT_AVAILABLE";
  case STATUS_ABIOS_INVALID_SELECTOR:                           return "STATUS_ABIOS_INVALID_SELECTOR";
  case STATUS_NO_LDT:                                           return "STATUS_NO_LDT";
  case STATUS_INVALID_LDT_SIZE:                                 return "STATUS_INVALID_LDT_SIZE";
  case STATUS_INVALID_LDT_OFFSET:                               return "STATUS_INVALID_LDT_OFFSET";
  case STATUS_INVALID_LDT_DESCRIPTOR:                           return "STATUS_INVALID_LDT_DESCRIPTOR";
  case STATUS_INVALID_IMAGE_NE_FORMAT:                          return "STATUS_INVALID_IMAGE_NE_FORMAT";
  case STATUS_RXACT_INVALID_STATE:                              return "STATUS_RXACT_INVALID_STATE";
  case STATUS_RXACT_COMMIT_FAILURE:                             return "STATUS_RXACT_COMMIT_FAILURE";
  case STATUS_MAPPED_FILE_SIZE_ZERO:                            return "STATUS_MAPPED_FILE_SIZE_ZERO";
  case STATUS_TOO_MANY_OPENED_FILES:                            return "STATUS_TOO_MANY_OPENED_FILES";
  case STATUS_CANCELLED:                                        return "STATUS_CANCELLED";
  case STATUS_CANNOT_DELETE:                                    return "STATUS_CANNOT_DELETE";
  case STATUS_INVALID_COMPUTER_NAME:                            return "STATUS_INVALID_COMPUTER_NAME";
  case STATUS_FILE_DELETED:                                     return "STATUS_FILE_DELETED";
  case STATUS_SPECIAL_ACCOUNT:                                  return "STATUS_SPECIAL_ACCOUNT";
  case STATUS_SPECIAL_GROUP:                                    return "STATUS_SPECIAL_GROUP";
  case STATUS_SPECIAL_USER:                                     return "STATUS_SPECIAL_USER";
  case STATUS_MEMBERS_PRIMARY_GROUP:                            return "STATUS_MEMBERS_PRIMARY_GROUP";
  case STATUS_FILE_CLOSED:                                      return "STATUS_FILE_CLOSED";
  case STATUS_TOO_MANY_THREADS:                                 return "STATUS_TOO_MANY_THREADS";
  case STATUS_THREAD_NOT_IN_PROCESS:                            return "STATUS_THREAD_NOT_IN_PROCESS";
  case STATUS_TOKEN_ALREADY_IN_USE:                             return "STATUS_TOKEN_ALREADY_IN_USE";
  case STATUS_PAGEFILE_QUOTA_EXCEEDED:                          return "STATUS_PAGEFILE_QUOTA_EXCEEDED";
  case STATUS_COMMITMENT_LIMIT:                                 return "STATUS_COMMITMENT_LIMIT";
  case STATUS_INVALID_IMAGE_LE_FORMAT:                          return "STATUS_INVALID_IMAGE_LE_FORMAT";
  case STATUS_INVALID_IMAGE_NOT_MZ:                             return "STATUS_INVALID_IMAGE_NOT_MZ";
  case STATUS_INVALID_IMAGE_PROTECT:                            return "STATUS_INVALID_IMAGE_PROTECT";
  case STATUS_INVALID_IMAGE_WIN_16:                             return "STATUS_INVALID_IMAGE_WIN_16";
  case STATUS_LOGON_SERVER_CONFLICT:                            return "STATUS_LOGON_SERVER_CONFLICT";
  case STATUS_TIME_DIFFERENCE_AT_DC:                            return "STATUS_TIME_DIFFERENCE_AT_DC";
  case STATUS_SYNCHRONIZATION_REQUIRED:                         return "STATUS_SYNCHRONIZATION_REQUIRED";
  case STATUS_DLL_NOT_FOUND:                                    return "STATUS_DLL_NOT_FOUND";
  case STATUS_OPEN_FAILED:                                      return "STATUS_OPEN_FAILED";
  case STATUS_IO_PRIVILEGE_FAILED:                              return "STATUS_IO_PRIVILEGE_FAILED";
  case STATUS_ORDINAL_NOT_FOUND:                                return "STATUS_ORDINAL_NOT_FOUND";
  case STATUS_ENTRYPOINT_NOT_FOUND:                             return "STATUS_ENTRYPOINT_NOT_FOUND";
  case STATUS_CONTROL_C_EXIT:                                   return "STATUS_CONTROL_C_EXIT";
  case STATUS_LOCAL_DISCONNECT:                                 return "STATUS_LOCAL_DISCONNECT";
  case STATUS_REMOTE_DISCONNECT:                                return "STATUS_REMOTE_DISCONNECT";
  case STATUS_REMOTE_RESOURCES:                                 return "STATUS_REMOTE_RESOURCES";
  case STATUS_LINK_FAILED:                                      return "STATUS_LINK_FAILED";
  case STATUS_LINK_TIMEOUT:                                     return "STATUS_LINK_TIMEOUT";
  case STATUS_INVALID_CONNECTION:                               return "STATUS_INVALID_CONNECTION";
  case STATUS_INVALID_ADDRESS:                                  return "STATUS_INVALID_ADDRESS";
  case STATUS_DLL_INIT_FAILED:                                  return "STATUS_DLL_INIT_FAILED";
  case STATUS_MISSING_SYSTEMFILE:                               return "STATUS_MISSING_SYSTEMFILE";
  case STATUS_UNHANDLED_EXCEPTION:                              return "STATUS_UNHANDLED_EXCEPTION";
  case STATUS_APP_INIT_FAILURE:                                 return "STATUS_APP_INIT_FAILURE";
  case STATUS_PAGEFILE_CREATE_FAILED:                           return "STATUS_PAGEFILE_CREATE_FAILED";
  case STATUS_NO_PAGEFILE:                                      return "STATUS_NO_PAGEFILE";
  case STATUS_INVALID_LEVEL:                                    return "STATUS_INVALID_LEVEL";
  case STATUS_WRONG_PASSWORD_CORE:                              return "STATUS_WRONG_PASSWORD_CORE";
  case STATUS_ILLEGAL_FLOAT_CONTEXT:                            return "STATUS_ILLEGAL_FLOAT_CONTEXT";
  case STATUS_PIPE_BROKEN:                                      return "STATUS_PIPE_BROKEN";
  case STATUS_REGISTRY_CORRUPT:                                 return "STATUS_REGISTRY_CORRUPT";
  case STATUS_REGISTRY_IO_FAILED:                               return "STATUS_REGISTRY_IO_FAILED";
  case STATUS_NO_EVENT_PAIR:                                    return "STATUS_NO_EVENT_PAIR";
  case STATUS_UNRECOGNIZED_VOLUME:                              return "STATUS_UNRECOGNIZED_VOLUME";
  case STATUS_SERIAL_NO_DEVICE_INITED:                          return "STATUS_SERIAL_NO_DEVICE_INITED";
  case STATUS_NO_SUCH_ALIAS:                                    return "STATUS_NO_SUCH_ALIAS";
  case STATUS_MEMBER_NOT_IN_ALIAS:                              return "STATUS_MEMBER_NOT_IN_ALIAS";
  case STATUS_MEMBER_IN_ALIAS:                                  return "STATUS_MEMBER_IN_ALIAS";
  case STATUS_ALIAS_EXISTS:                                     return "STATUS_ALIAS_EXISTS";
  case STATUS_LOGON_NOT_GRANTED:                                return "STATUS_LOGON_NOT_GRANTED";
  case STATUS_TOO_MANY_SECRETS:                                 return "STATUS_TOO_MANY_SECRETS";
  case STATUS_SECRET_TOO_LONG:                                  return "STATUS_SECRET_TOO_LONG";
  case STATUS_INTERNAL_DB_ERROR:                                return "STATUS_INTERNAL_DB_ERROR";
  case STATUS_FULLSCREEN_MODE:                                  return "STATUS_FULLSCREEN_MODE";
  case STATUS_TOO_MANY_CONTEXT_IDS:                             return "STATUS_TOO_MANY_CONTEXT_IDS";
  case STATUS_LOGON_TYPE_NOT_GRANTED:                           return "STATUS_LOGON_TYPE_NOT_GRANTED";
  case STATUS_NOT_REGISTRY_FILE:                                return "STATUS_NOT_REGISTRY_FILE";
  case STATUS_NT_CROSS_ENCRYPTION_REQUIRED:                     return "STATUS_NT_CROSS_ENCRYPTION_REQUIRED";
  case STATUS_DOMAIN_CTRLR_CONFIG_ERROR:                        return "STATUS_DOMAIN_CTRLR_CONFIG_ERROR";
  case STATUS_FT_MISSING_MEMBER:                                return "STATUS_FT_MISSING_MEMBER";
  case STATUS_ILL_FORMED_SERVICE_ENTRY:                         return "STATUS_ILL_FORMED_SERVICE_ENTRY";
  case STATUS_ILLEGAL_CHARACTER:                                return "STATUS_ILLEGAL_CHARACTER";
  case STATUS_UNMAPPABLE_CHARACTER:                             return "STATUS_UNMAPPABLE_CHARACTER";
  case STATUS_UNDEFINED_CHARACTER:                              return "STATUS_UNDEFINED_CHARACTER";
  case STATUS_FLOPPY_VOLUME:                                    return "STATUS_FLOPPY_VOLUME";
  case STATUS_FLOPPY_ID_MARK_NOT_FOUND:                         return "STATUS_FLOPPY_ID_MARK_NOT_FOUND";
  case STATUS_FLOPPY_WRONG_CYLINDER:                            return "STATUS_FLOPPY_WRONG_CYLINDER";
  case STATUS_FLOPPY_UNKNOWN_ERROR:                             return "STATUS_FLOPPY_UNKNOWN_ERROR";
  case STATUS_FLOPPY_BAD_REGISTERS:                             return "STATUS_FLOPPY_BAD_REGISTERS";
  case STATUS_DISK_RECALIBRATE_FAILED:                          return "STATUS_DISK_RECALIBRATE_FAILED";
  case STATUS_DISK_OPERATION_FAILED:                            return "STATUS_DISK_OPERATION_FAILED";
  case STATUS_DISK_RESET_FAILED:                                return "STATUS_DISK_RESET_FAILED";
  case STATUS_SHARED_IRQ_BUSY:                                  return "STATUS_SHARED_IRQ_BUSY";
  case STATUS_FT_ORPHANING:                                     return "STATUS_FT_ORPHANING";
  case STATUS_BIOS_FAILED_TO_CONNECT_INTERRUPT:                 return "STATUS_BIOS_FAILED_TO_CONNECT_INTERRUPT";
  case STATUS_PARTITION_FAILURE:                                return "STATUS_PARTITION_FAILURE";
  case STATUS_INVALID_BLOCK_LENGTH:                             return "STATUS_INVALID_BLOCK_LENGTH";
  case STATUS_DEVICE_NOT_PARTITIONED:                           return "STATUS_DEVICE_NOT_PARTITIONED";
  case STATUS_UNABLE_TO_LOCK_MEDIA:                             return "STATUS_UNABLE_TO_LOCK_MEDIA";
  case STATUS_UNABLE_TO_UNLOAD_MEDIA:                           return "STATUS_UNABLE_TO_UNLOAD_MEDIA";
  case STATUS_EOM_OVERFLOW:                                     return "STATUS_EOM_OVERFLOW";
  case STATUS_NO_MEDIA:                                         return "STATUS_NO_MEDIA";
  case STATUS_NO_SUCH_MEMBER:                                   return "STATUS_NO_SUCH_MEMBER";
  case STATUS_INVALID_MEMBER:                                   return "STATUS_INVALID_MEMBER";
  case STATUS_KEY_DELETED:                                      return "STATUS_KEY_DELETED";
  case STATUS_NO_LOG_SPACE:                                     return "STATUS_NO_LOG_SPACE";
  case STATUS_TOO_MANY_SIDS:                                    return "STATUS_TOO_MANY_SIDS";
  case STATUS_LM_CROSS_ENCRYPTION_REQUIRED:                     return "STATUS_LM_CROSS_ENCRYPTION_REQUIRED";
  case STATUS_KEY_HAS_CHILDREN:                                 return "STATUS_KEY_HAS_CHILDREN";
  case STATUS_CHILD_MUST_BE_VOLATILE:                           return "STATUS_CHILD_MUST_BE_VOLATILE";
  case STATUS_DEVICE_CONFIGURATION_ERROR:                       return "STATUS_DEVICE_CONFIGURATION_ERROR";
  case STATUS_DRIVER_INTERNAL_ERROR:                            return "STATUS_DRIVER_INTERNAL_ERROR";
  case STATUS_INVALID_DEVICE_STATE:                             return "STATUS_INVALID_DEVICE_STATE";
  case STATUS_IO_DEVICE_ERROR:                                  return "STATUS_IO_DEVICE_ERROR";
  case STATUS_DEVICE_PROTOCOL_ERROR:                            return "STATUS_DEVICE_PROTOCOL_ERROR";
  case STATUS_BACKUP_CONTROLLER:                                return "STATUS_BACKUP_CONTROLLER";
  case STATUS_LOG_FILE_FULL:                                    return "STATUS_LOG_FILE_FULL";
  case STATUS_TOO_LATE:                                         return "STATUS_TOO_LATE";
  case STATUS_NO_TRUST_LSA_SECRET:                              return "STATUS_NO_TRUST_LSA_SECRET";
  case STATUS_NO_TRUST_SAM_ACCOUNT:                             return "STATUS_NO_TRUST_SAM_ACCOUNT";
  case STATUS_TRUSTED_DOMAIN_FAILURE:                           return "STATUS_TRUSTED_DOMAIN_FAILURE";
  case STATUS_TRUSTED_RELATIONSHIP_FAILURE:                     return "STATUS_TRUSTED_RELATIONSHIP_FAILURE";
  case STATUS_EVENTLOG_FILE_CORRUPT:                            return "STATUS_EVENTLOG_FILE_CORRUPT";
  case STATUS_EVENTLOG_CANT_START:                              return "STATUS_EVENTLOG_CANT_START";
  case STATUS_TRUST_FAILURE:                                    return "STATUS_TRUST_FAILURE";
  case STATUS_MUTANT_LIMIT_EXCEEDED:                            return "STATUS_MUTANT_LIMIT_EXCEEDED";
  case STATUS_NETLOGON_NOT_STARTED:                             return "STATUS_NETLOGON_NOT_STARTED";
  case STATUS_ACCOUNT_EXPIRED:                                  return "STATUS_ACCOUNT_EXPIRED";
  case STATUS_POSSIBLE_DEADLOCK:                                return "STATUS_POSSIBLE_DEADLOCK";
  case STATUS_NETWORK_CREDENTIAL_CONFLICT:                      return "STATUS_NETWORK_CREDENTIAL_CONFLICT";
  case STATUS_REMOTE_SESSION_LIMIT:                             return "STATUS_REMOTE_SESSION_LIMIT";
  case STATUS_EVENTLOG_FILE_CHANGED:                            return "STATUS_EVENTLOG_FILE_CHANGED";
  case STATUS_NOLOGON_INTERDOMAIN_TRUST_ACCOUNT:                return "STATUS_NOLOGON_INTERDOMAIN_TRUST_ACCOUNT";
  case STATUS_NOLOGON_WORKSTATION_TRUST_ACCOUNT:                return "STATUS_NOLOGON_WORKSTATION_TRUST_ACCOUNT";
  case STATUS_NOLOGON_SERVER_TRUST_ACCOUNT:                     return "STATUS_NOLOGON_SERVER_TRUST_ACCOUNT";
  case STATUS_DOMAIN_TRUST_INCONSISTENT:                        return "STATUS_DOMAIN_TRUST_INCONSISTENT";
  case STATUS_FS_DRIVER_REQUIRED:                               return "STATUS_FS_DRIVER_REQUIRED";
  case STATUS_NO_USER_SESSION_KEY:                              return "STATUS_NO_USER_SESSION_KEY";
  case STATUS_USER_SESSION_DELETED:                             return "STATUS_USER_SESSION_DELETED";
  case STATUS_RESOURCE_LANG_NOT_FOUND:                          return "STATUS_RESOURCE_LANG_NOT_FOUND";
  case STATUS_INSUFF_SERVER_RESOURCES:                          return "STATUS_INSUFF_SERVER_RESOURCES";
  case STATUS_INVALID_BUFFER_SIZE:                              return "STATUS_INVALID_BUFFER_SIZE";
  case STATUS_INVALID_ADDRESS_COMPONENT:                        return "STATUS_INVALID_ADDRESS_COMPONENT";
  case STATUS_INVALID_ADDRESS_WILDCARD:                         return "STATUS_INVALID_ADDRESS_WILDCARD";
  case STATUS_TOO_MANY_ADDRESSES:                               return "STATUS_TOO_MANY_ADDRESSES";
  case STATUS_ADDRESS_ALREADY_EXISTS:                           return "STATUS_ADDRESS_ALREADY_EXISTS";
  case STATUS_ADDRESS_CLOSED:                                   return "STATUS_ADDRESS_CLOSED";
  case STATUS_CONNECTION_DISCONNECTED:                          return "STATUS_CONNECTION_DISCONNECTED";
  case STATUS_CONNECTION_RESET:                                 return "STATUS_CONNECTION_RESET";
  case STATUS_TOO_MANY_NODES:                                   return "STATUS_TOO_MANY_NODES";
  case STATUS_TRANSACTION_ABORTED:                              return "STATUS_TRANSACTION_ABORTED";
  case STATUS_TRANSACTION_TIMED_OUT:                            return "STATUS_TRANSACTION_TIMED_OUT";
  case STATUS_TRANSACTION_NO_RELEASE:                           return "STATUS_TRANSACTION_NO_RELEASE";
  case STATUS_TRANSACTION_NO_MATCH:                             return "STATUS_TRANSACTION_NO_MATCH";
  case STATUS_TRANSACTION_RESPONDED:                            return "STATUS_TRANSACTION_RESPONDED";
  case STATUS_TRANSACTION_INVALID_ID:                           return "STATUS_TRANSACTION_INVALID_ID";
  case STATUS_TRANSACTION_INVALID_TYPE:                         return "STATUS_TRANSACTION_INVALID_TYPE";
  case STATUS_NOT_SERVER_SESSION:                               return "STATUS_NOT_SERVER_SESSION";
  case STATUS_NOT_CLIENT_SESSION:                               return "STATUS_NOT_CLIENT_SESSION";
  case STATUS_CANNOT_LOAD_REGISTRY_FILE:                        return "STATUS_CANNOT_LOAD_REGISTRY_FILE";
  case STATUS_DEBUG_ATTACH_FAILED:                              return "STATUS_DEBUG_ATTACH_FAILED";
  case STATUS_SYSTEM_PROCESS_TERMINATED:                        return "STATUS_SYSTEM_PROCESS_TERMINATED";
  case STATUS_DATA_NOT_ACCEPTED:                                return "STATUS_DATA_NOT_ACCEPTED";
  case STATUS_NO_BROWSER_SERVERS_FOUND:                         return "STATUS_NO_BROWSER_SERVERS_FOUND";
  case STATUS_VDM_HARD_ERROR:                                   return "STATUS_VDM_HARD_ERROR";
  case STATUS_DRIVER_CANCEL_TIMEOUT:                            return "STATUS_DRIVER_CANCEL_TIMEOUT";
  case STATUS_REPLY_MESSAGE_MISMATCH:                           return "STATUS_REPLY_MESSAGE_MISMATCH";
  case STATUS_MAPPED_ALIGNMENT:                                 return "STATUS_MAPPED_ALIGNMENT";
  case STATUS_IMAGE_CHECKSUM_MISMATCH:                          return "STATUS_IMAGE_CHECKSUM_MISMATCH";
  case STATUS_LOST_WRITEBEHIND_DATA:                            return "STATUS_LOST_WRITEBEHIND_DATA";
  case STATUS_CLIENT_SERVER_PARAMETERS_INVALID:                 return "STATUS_CLIENT_SERVER_PARAMETERS_INVALID";
  case STATUS_PASSWORD_MUST_CHANGE:                             return "STATUS_PASSWORD_MUST_CHANGE";
  case STATUS_NOT_FOUND:                                        return "STATUS_NOT_FOUND";
  case STATUS_NOT_TINY_STREAM:                                  return "STATUS_NOT_TINY_STREAM";
  case STATUS_RECOVERY_FAILURE:                                 return "STATUS_RECOVERY_FAILURE";
  case STATUS_STACK_OVERFLOW_READ:                              return "STATUS_STACK_OVERFLOW_READ";
  case STATUS_FAIL_CHECK:                                       return "STATUS_FAIL_CHECK";
  case STATUS_DUPLICATE_OBJECTID:                               return "STATUS_DUPLICATE_OBJECTID";
  case STATUS_OBJECTID_EXISTS:                                  return "STATUS_OBJECTID_EXISTS";
  case STATUS_CONVERT_TO_LARGE:                                 return "STATUS_CONVERT_TO_LARGE";
  case STATUS_RETRY:                                            return "STATUS_RETRY";
  case STATUS_FOUND_OUT_OF_SCOPE:                               return "STATUS_FOUND_OUT_OF_SCOPE";
  case STATUS_ALLOCATE_BUCKET:                                  return "STATUS_ALLOCATE_BUCKET";
  case STATUS_PROPSET_NOT_FOUND:                                return "STATUS_PROPSET_NOT_FOUND";
  case STATUS_MARSHALL_OVERFLOW:                                return "STATUS_MARSHALL_OVERFLOW";
  case STATUS_INVALID_VARIANT:                                  return "STATUS_INVALID_VARIANT";
  case STATUS_DOMAIN_CONTROLLER_NOT_FOUND:                      return "STATUS_DOMAIN_CONTROLLER_NOT_FOUND";
  case STATUS_ACCOUNT_LOCKED_OUT:                               return "STATUS_ACCOUNT_LOCKED_OUT";
  case STATUS_HANDLE_NOT_CLOSABLE:                              return "STATUS_HANDLE_NOT_CLOSABLE";
  case STATUS_CONNECTION_REFUSED:                               return "STATUS_CONNECTION_REFUSED";
  case STATUS_GRACEFUL_DISCONNECT:                              return "STATUS_GRACEFUL_DISCONNECT";
  case STATUS_ADDRESS_ALREADY_ASSOCIATED:                       return "STATUS_ADDRESS_ALREADY_ASSOCIATED";
  case STATUS_ADDRESS_NOT_ASSOCIATED:                           return "STATUS_ADDRESS_NOT_ASSOCIATED";
  case STATUS_CONNECTION_INVALID:                               return "STATUS_CONNECTION_INVALID";
  case STATUS_CONNECTION_ACTIVE:                                return "STATUS_CONNECTION_ACTIVE";
  case STATUS_NETWORK_UNREACHABLE:                              return "STATUS_NETWORK_UNREACHABLE";
  case STATUS_HOST_UNREACHABLE:                                 return "STATUS_HOST_UNREACHABLE";
  case STATUS_PROTOCOL_UNREACHABLE:                             return "STATUS_PROTOCOL_UNREACHABLE";
  case STATUS_PORT_UNREACHABLE:                                 return "STATUS_PORT_UNREACHABLE";
  case STATUS_REQUEST_ABORTED:                                  return "STATUS_REQUEST_ABORTED";
  case STATUS_CONNECTION_ABORTED:                               return "STATUS_CONNECTION_ABORTED";
  case STATUS_BAD_COMPRESSION_BUFFER:                           return "STATUS_BAD_COMPRESSION_BUFFER";
  case STATUS_USER_MAPPED_FILE:                                 return "STATUS_USER_MAPPED_FILE";
  case STATUS_AUDIT_FAILED:                                     return "STATUS_AUDIT_FAILED";
  case STATUS_TIMER_RESOLUTION_NOT_SET:                         return "STATUS_TIMER_RESOLUTION_NOT_SET";
  case STATUS_CONNECTION_COUNT_LIMIT:                           return "STATUS_CONNECTION_COUNT_LIMIT";
  case STATUS_LOGIN_TIME_RESTRICTION:                           return "STATUS_LOGIN_TIME_RESTRICTION";
  case STATUS_LOGIN_WKSTA_RESTRICTION:                          return "STATUS_LOGIN_WKSTA_RESTRICTION";
  case STATUS_IMAGE_MP_UP_MISMATCH:                             return "STATUS_IMAGE_MP_UP_MISMATCH";
  case STATUS_INSUFFICIENT_LOGON_INFO:                          return "STATUS_INSUFFICIENT_LOGON_INFO";
  case STATUS_BAD_DLL_ENTRYPOINT:                               return "STATUS_BAD_DLL_ENTRYPOINT";
  case STATUS_BAD_SERVICE_ENTRYPOINT:                           return "STATUS_BAD_SERVICE_ENTRYPOINT";
  case STATUS_LPC_REPLY_LOST:                                   return "STATUS_LPC_REPLY_LOST";
  case STATUS_IP_ADDRESS_CONFLICT1:                             return "STATUS_IP_ADDRESS_CONFLICT1";
  case STATUS_IP_ADDRESS_CONFLICT2:                             return "STATUS_IP_ADDRESS_CONFLICT2";
  case STATUS_REGISTRY_QUOTA_LIMIT:                             return "STATUS_REGISTRY_QUOTA_LIMIT";
  case STATUS_PATH_NOT_COVERED:                                 return "STATUS_PATH_NOT_COVERED";
  case STATUS_NO_CALLBACK_ACTIVE:                               return "STATUS_NO_CALLBACK_ACTIVE";
  case STATUS_LICENSE_QUOTA_EXCEEDED:                           return "STATUS_LICENSE_QUOTA_EXCEEDED";
  case STATUS_PWD_TOO_SHORT:                                    return "STATUS_PWD_TOO_SHORT";
  case STATUS_PWD_TOO_RECENT:                                   return "STATUS_PWD_TOO_RECENT";
  case STATUS_PWD_HISTORY_CONFLICT:                             return "STATUS_PWD_HISTORY_CONFLICT";
  case STATUS_PLUGPLAY_NO_DEVICE:                               return "STATUS_PLUGPLAY_NO_DEVICE";
  case STATUS_UNSUPPORTED_COMPRESSION:                          return "STATUS_UNSUPPORTED_COMPRESSION";
  case STATUS_INVALID_HW_PROFILE:                               return "STATUS_INVALID_HW_PROFILE";
  case STATUS_INVALID_PLUGPLAY_DEVICE_PATH:                     return "STATUS_INVALID_PLUGPLAY_DEVICE_PATH";
  case STATUS_DRIVER_ORDINAL_NOT_FOUND:                         return "STATUS_DRIVER_ORDINAL_NOT_FOUND";
  case STATUS_DRIVER_ENTRYPOINT_NOT_FOUND:                      return "STATUS_DRIVER_ENTRYPOINT_NOT_FOUND";
  case STATUS_RESOURCE_NOT_OWNED:                               return "STATUS_RESOURCE_NOT_OWNED";
  case STATUS_TOO_MANY_LINKS:                                   return "STATUS_TOO_MANY_LINKS";
  case STATUS_QUOTA_LIST_INCONSISTENT:                          return "STATUS_QUOTA_LIST_INCONSISTENT";
  case STATUS_FILE_IS_OFFLINE:                                  return "STATUS_FILE_IS_OFFLINE";
  case STATUS_EVALUATION_EXPIRATION:                            return "STATUS_EVALUATION_EXPIRATION";
  case STATUS_ILLEGAL_DLL_RELOCATION:                           return "STATUS_ILLEGAL_DLL_RELOCATION";
  case STATUS_LICENSE_VIOLATION:                                return "STATUS_LICENSE_VIOLATION";
  case STATUS_DLL_INIT_FAILED_LOGOFF:                           return "STATUS_DLL_INIT_FAILED_LOGOFF";
  case STATUS_DRIVER_UNABLE_TO_LOAD:                            return "STATUS_DRIVER_UNABLE_TO_LOAD";
  case STATUS_DFS_UNAVAILABLE:                                  return "STATUS_DFS_UNAVAILABLE";
  case STATUS_VOLUME_DISMOUNTED:                                return "STATUS_VOLUME_DISMOUNTED";
  case STATUS_WX86_INTERNAL_ERROR:                              return "STATUS_WX86_INTERNAL_ERROR";
  case STATUS_WX86_FLOAT_STACK_CHECK:                           return "STATUS_WX86_FLOAT_STACK_CHECK";
  case STATUS_VALIDATE_CONTINUE:                                return "STATUS_VALIDATE_CONTINUE";
  case STATUS_NO_MATCH:                                         return "STATUS_NO_MATCH";
  case STATUS_NO_MORE_MATCHES:                                  return "STATUS_NO_MORE_MATCHES";
  case STATUS_NOT_A_REPARSE_POINT:                              return "STATUS_NOT_A_REPARSE_POINT";
  case STATUS_IO_REPARSE_TAG_INVALID:                           return "STATUS_IO_REPARSE_TAG_INVALID";
  case STATUS_IO_REPARSE_TAG_MISMATCH:                          return "STATUS_IO_REPARSE_TAG_MISMATCH";
  case STATUS_IO_REPARSE_DATA_INVALID:                          return "STATUS_IO_REPARSE_DATA_INVALID";
  case STATUS_IO_REPARSE_TAG_NOT_HANDLED:                       return "STATUS_IO_REPARSE_TAG_NOT_HANDLED";
  case STATUS_REPARSE_POINT_NOT_RESOLVED:                       return "STATUS_REPARSE_POINT_NOT_RESOLVED";
  case STATUS_DIRECTORY_IS_A_REPARSE_POINT:                     return "STATUS_DIRECTORY_IS_A_REPARSE_POINT";
  case STATUS_RANGE_LIST_CONFLICT:                              return "STATUS_RANGE_LIST_CONFLICT";
  case STATUS_SOURCE_ELEMENT_EMPTY:                             return "STATUS_SOURCE_ELEMENT_EMPTY";
  case STATUS_DESTINATION_ELEMENT_FULL:                         return "STATUS_DESTINATION_ELEMENT_FULL";
  case STATUS_ILLEGAL_ELEMENT_ADDRESS:                          return "STATUS_ILLEGAL_ELEMENT_ADDRESS";
  case STATUS_MAGAZINE_NOT_PRESENT:                             return "STATUS_MAGAZINE_NOT_PRESENT";
  case STATUS_REINITIALIZATION_NEEDED:                          return "STATUS_REINITIALIZATION_NEEDED";
  case STATUS_DEVICE_REQUIRES_CLEANING:                         return "STATUS_DEVICE_REQUIRES_CLEANING";
  case STATUS_DEVICE_DOOR_OPEN:                                 return "STATUS_DEVICE_DOOR_OPEN";
  case STATUS_ENCRYPTION_FAILED:                                return "STATUS_ENCRYPTION_FAILED";
  case STATUS_DECRYPTION_FAILED:                                return "STATUS_DECRYPTION_FAILED";
  case STATUS_RANGE_NOT_FOUND:                                  return "STATUS_RANGE_NOT_FOUND";
  case STATUS_NO_RECOVERY_POLICY:                               return "STATUS_NO_RECOVERY_POLICY";
  case STATUS_NO_EFS:                                           return "STATUS_NO_EFS";
  case STATUS_WRONG_EFS:                                        return "STATUS_WRONG_EFS";
  case STATUS_NO_USER_KEYS:                                     return "STATUS_NO_USER_KEYS";
  case STATUS_FILE_NOT_ENCRYPTED:                               return "STATUS_FILE_NOT_ENCRYPTED";
  case STATUS_NOT_EXPORT_FORMAT:                                return "STATUS_NOT_EXPORT_FORMAT";
  case STATUS_FILE_ENCRYPTED:                                   return "STATUS_FILE_ENCRYPTED";
  case STATUS_WAKE_SYSTEM:                                      return "STATUS_WAKE_SYSTEM";
  case STATUS_WMI_GUID_NOT_FOUND:                               return "STATUS_WMI_GUID_NOT_FOUND";
  case STATUS_WMI_INSTANCE_NOT_FOUND:                           return "STATUS_WMI_INSTANCE_NOT_FOUND";
  case STATUS_WMI_ITEMID_NOT_FOUND:                             return "STATUS_WMI_ITEMID_NOT_FOUND";
  case STATUS_WMI_TRY_AGAIN:                                    return "STATUS_WMI_TRY_AGAIN";
  case STATUS_SHARED_POLICY:                                    return "STATUS_SHARED_POLICY";
  case STATUS_POLICY_OBJECT_NOT_FOUND:                          return "STATUS_POLICY_OBJECT_NOT_FOUND";
  case STATUS_POLICY_ONLY_IN_DS:                                return "STATUS_POLICY_ONLY_IN_DS";
  case STATUS_VOLUME_NOT_UPGRADED:                              return "STATUS_VOLUME_NOT_UPGRADED";
  case STATUS_REMOTE_STORAGE_NOT_ACTIVE:                        return "STATUS_REMOTE_STORAGE_NOT_ACTIVE";
  case STATUS_REMOTE_STORAGE_MEDIA_ERROR:                       return "STATUS_REMOTE_STORAGE_MEDIA_ERROR";
  case STATUS_NO_TRACKING_SERVICE:                              return "STATUS_NO_TRACKING_SERVICE";
  case STATUS_SERVER_SID_MISMATCH:                              return "STATUS_SERVER_SID_MISMATCH";
  case STATUS_DS_NO_ATTRIBUTE_OR_VALUE:                         return "STATUS_DS_NO_ATTRIBUTE_OR_VALUE";
  case STATUS_DS_INVALID_ATTRIBUTE_SYNTAX:                      return "STATUS_DS_INVALID_ATTRIBUTE_SYNTAX";
  case STATUS_DS_ATTRIBUTE_TYPE_UNDEFINED:                      return "STATUS_DS_ATTRIBUTE_TYPE_UNDEFINED";
  case STATUS_DS_ATTRIBUTE_OR_VALUE_EXISTS:                     return "STATUS_DS_ATTRIBUTE_OR_VALUE_EXISTS";
  case STATUS_DS_BUSY:                                          return "STATUS_DS_BUSY";
  case STATUS_DS_UNAVAILABLE:                                   return "STATUS_DS_UNAVAILABLE";
  case STATUS_DS_NO_RIDS_ALLOCATED:                             return "STATUS_DS_NO_RIDS_ALLOCATED";
  case STATUS_DS_NO_MORE_RIDS:                                  return "STATUS_DS_NO_MORE_RIDS";
  case STATUS_DS_INCORRECT_ROLE_OWNER:                          return "STATUS_DS_INCORRECT_ROLE_OWNER";
  case STATUS_DS_RIDMGR_INIT_ERROR:                             return "STATUS_DS_RIDMGR_INIT_ERROR";
  case STATUS_DS_OBJ_CLASS_VIOLATION:                           return "STATUS_DS_OBJ_CLASS_VIOLATION";
  case STATUS_DS_CANT_ON_NON_LEAF:                              return "STATUS_DS_CANT_ON_NON_LEAF";
  case STATUS_DS_CANT_ON_RDN:                                   return "STATUS_DS_CANT_ON_RDN";
  case STATUS_DS_CANT_MOD_OBJ_CLASS:                            return "STATUS_DS_CANT_MOD_OBJ_CLASS";
  case STATUS_DS_CROSS_DOM_MOVE_FAILED:                         return "STATUS_DS_CROSS_DOM_MOVE_FAILED";
  case STATUS_DS_GC_NOT_AVAILABLE:                              return "STATUS_DS_GC_NOT_AVAILABLE";
  case STATUS_DIRECTORY_SERVICE_REQUIRED:                       return "STATUS_DIRECTORY_SERVICE_REQUIRED";
  case STATUS_REPARSE_ATTRIBUTE_CONFLICT:                       return "STATUS_REPARSE_ATTRIBUTE_CONFLICT";
  case STATUS_CANT_ENABLE_DENY_ONLY:                            return "STATUS_CANT_ENABLE_DENY_ONLY";
  case STATUS_FLOAT_MULTIPLE_FAULTS:                            return "STATUS_FLOAT_MULTIPLE_FAULTS";
  case STATUS_FLOAT_MULTIPLE_TRAPS:                             return "STATUS_FLOAT_MULTIPLE_TRAPS";
  case STATUS_DEVICE_REMOVED:                                   return "STATUS_DEVICE_REMOVED";
  case STATUS_JOURNAL_DELETE_IN_PROGRESS:                       return "STATUS_JOURNAL_DELETE_IN_PROGRESS";
  case STATUS_JOURNAL_NOT_ACTIVE:                               return "STATUS_JOURNAL_NOT_ACTIVE";
  case STATUS_NOINTERFACE:                                      return "STATUS_NOINTERFACE";
  case STATUS_DS_ADMIN_LIMIT_EXCEEDED:                          return "STATUS_DS_ADMIN_LIMIT_EXCEEDED";
  case STATUS_DRIVER_FAILED_SLEEP:                              return "STATUS_DRIVER_FAILED_SLEEP";
  case STATUS_MUTUAL_AUTHENTICATION_FAILED:                     return "STATUS_MUTUAL_AUTHENTICATION_FAILED";
  case STATUS_CORRUPT_SYSTEM_FILE:                              return "STATUS_CORRUPT_SYSTEM_FILE";
  case STATUS_DATATYPE_MISALIGNMENT_ERROR:                      return "STATUS_DATATYPE_MISALIGNMENT_ERROR";
  case STATUS_WMI_READ_ONLY:                                    return "STATUS_WMI_READ_ONLY";
  case STATUS_WMI_SET_FAILURE:                                  return "STATUS_WMI_SET_FAILURE";
  case STATUS_COMMITMENT_MINIMUM:                               return "STATUS_COMMITMENT_MINIMUM";
  case STATUS_REG_NAT_CONSUMPTION:                              return "STATUS_REG_NAT_CONSUMPTION";
  case STATUS_TRANSPORT_FULL:                                   return "STATUS_TRANSPORT_FULL";
  case STATUS_DS_SAM_INIT_FAILURE:                              return "STATUS_DS_SAM_INIT_FAILURE";
  case STATUS_ONLY_IF_CONNECTED:                                return "STATUS_ONLY_IF_CONNECTED";
  case STATUS_DS_SENSITIVE_GROUP_VIOLATION:                     return "STATUS_DS_SENSITIVE_GROUP_VIOLATION";
  case STATUS_PNP_RESTART_ENUMERATION:                          return "STATUS_PNP_RESTART_ENUMERATION";
  case STATUS_JOURNAL_ENTRY_DELETED:                            return "STATUS_JOURNAL_ENTRY_DELETED";
  case STATUS_DS_CANT_MOD_PRIMARYGROUPID:                       return "STATUS_DS_CANT_MOD_PRIMARYGROUPID";
  case STATUS_SYSTEM_IMAGE_BAD_SIGNATURE:                       return "STATUS_SYSTEM_IMAGE_BAD_SIGNATURE";
  case STATUS_PNP_REBOOT_REQUIRED:                              return "STATUS_PNP_REBOOT_REQUIRED";
  case STATUS_POWER_STATE_INVALID:                              return "STATUS_POWER_STATE_INVALID";
  case STATUS_DS_INVALID_GROUP_TYPE:                            return "STATUS_DS_INVALID_GROUP_TYPE";
  case STATUS_DS_NO_NEST_GLOBALGROUP_IN_MIXEDDOMAIN:            return "STATUS_DS_NO_NEST_GLOBALGROUP_IN_MIXEDDOMAIN";
  case STATUS_DS_NO_NEST_LOCALGROUP_IN_MIXEDDOMAIN:             return "STATUS_DS_NO_NEST_LOCALGROUP_IN_MIXEDDOMAIN";
  case STATUS_DS_GLOBAL_CANT_HAVE_LOCAL_MEMBER:                 return "STATUS_DS_GLOBAL_CANT_HAVE_LOCAL_MEMBER";
  case STATUS_DS_GLOBAL_CANT_HAVE_UNIVERSAL_MEMBER:             return "STATUS_DS_GLOBAL_CANT_HAVE_UNIVERSAL_MEMBER";
  case STATUS_DS_UNIVERSAL_CANT_HAVE_LOCAL_MEMBER:              return "STATUS_DS_UNIVERSAL_CANT_HAVE_LOCAL_MEMBER";
  case STATUS_DS_GLOBAL_CANT_HAVE_CROSSDOMAIN_MEMBER:           return "STATUS_DS_GLOBAL_CANT_HAVE_CROSSDOMAIN_MEMBER";
  case STATUS_DS_LOCAL_CANT_HAVE_CROSSDOMAIN_LOCAL_MEMBER:      return "STATUS_DS_LOCAL_CANT_HAVE_CROSSDOMAIN_LOCAL_MEMBER";
  case STATUS_DS_HAVE_PRIMARY_MEMBERS:                          return "STATUS_DS_HAVE_PRIMARY_MEMBERS";
  case STATUS_WMI_NOT_SUPPORTED:                                return "STATUS_WMI_NOT_SUPPORTED";
  case STATUS_INSUFFICIENT_POWER:                               return "STATUS_INSUFFICIENT_POWER";
  case STATUS_SAM_NEED_BOOTKEY_PASSWORD:                        return "STATUS_SAM_NEED_BOOTKEY_PASSWORD";
  case STATUS_SAM_NEED_BOOTKEY_FLOPPY:                          return "STATUS_SAM_NEED_BOOTKEY_FLOPPY";
  case STATUS_DS_CANT_START:                                    return "STATUS_DS_CANT_START";
  case STATUS_DS_INIT_FAILURE:                                  return "STATUS_DS_INIT_FAILURE";
  case STATUS_SAM_INIT_FAILURE:                                 return "STATUS_SAM_INIT_FAILURE";
  case STATUS_DS_GC_REQUIRED:                                   return "STATUS_DS_GC_REQUIRED";
  case STATUS_DS_LOCAL_MEMBER_OF_LOCAL_ONLY:                    return "STATUS_DS_LOCAL_MEMBER_OF_LOCAL_ONLY";
  case STATUS_DS_NO_FPO_IN_UNIVERSAL_GROUPS:                    return "STATUS_DS_NO_FPO_IN_UNIVERSAL_GROUPS";
  case STATUS_DS_MACHINE_ACCOUNT_QUOTA_EXCEEDED:                return "STATUS_DS_MACHINE_ACCOUNT_QUOTA_EXCEEDED";
  case STATUS_MULTIPLE_FAULT_VIOLATION:                         return "STATUS_MULTIPLE_FAULT_VIOLATION";
  case STATUS_CURRENT_DOMAIN_NOT_ALLOWED:                       return "STATUS_CURRENT_DOMAIN_NOT_ALLOWED";
  case STATUS_CANNOT_MAKE:                                      return "STATUS_CANNOT_MAKE";
  case STATUS_SYSTEM_SHUTDOWN:                                  return "STATUS_SYSTEM_SHUTDOWN";
  case STATUS_DS_INIT_FAILURE_CONSOLE:                          return "STATUS_DS_INIT_FAILURE_CONSOLE";
  case STATUS_DS_SAM_INIT_FAILURE_CONSOLE:                      return "STATUS_DS_SAM_INIT_FAILURE_CONSOLE";
  case STATUS_UNFINISHED_CONTEXT_DELETED:                       return "STATUS_UNFINISHED_CONTEXT_DELETED";
  case STATUS_NO_TGT_REPLY:                                     return "STATUS_NO_TGT_REPLY";
  case STATUS_OBJECTID_NOT_FOUND:                               return "STATUS_OBJECTID_NOT_FOUND";
  case STATUS_NO_IP_ADDRESSES:                                  return "STATUS_NO_IP_ADDRESSES";
  case STATUS_WRONG_CREDENTIAL_HANDLE:                          return "STATUS_WRONG_CREDENTIAL_HANDLE";
  case STATUS_CRYPTO_SYSTEM_INVALID:                            return "STATUS_CRYPTO_SYSTEM_INVALID";
  case STATUS_MAX_REFERRALS_EXCEEDED:                           return "STATUS_MAX_REFERRALS_EXCEEDED";
  case STATUS_MUST_BE_KDC:                                      return "STATUS_MUST_BE_KDC";
  case STATUS_STRONG_CRYPTO_NOT_SUPPORTED:                      return "STATUS_STRONG_CRYPTO_NOT_SUPPORTED";
  case STATUS_TOO_MANY_PRINCIPALS:                              return "STATUS_TOO_MANY_PRINCIPALS";
  case STATUS_NO_PA_DATA:                                       return "STATUS_NO_PA_DATA";
  case STATUS_PKINIT_NAME_MISMATCH:                             return "STATUS_PKINIT_NAME_MISMATCH";
  case STATUS_SMARTCARD_LOGON_REQUIRED:                         return "STATUS_SMARTCARD_LOGON_REQUIRED";
  case STATUS_KDC_INVALID_REQUEST:                              return "STATUS_KDC_INVALID_REQUEST";
  case STATUS_KDC_UNABLE_TO_REFER:                              return "STATUS_KDC_UNABLE_TO_REFER";
  case STATUS_KDC_UNKNOWN_ETYPE:                                return "STATUS_KDC_UNKNOWN_ETYPE";
  case STATUS_SHUTDOWN_IN_PROGRESS:                             return "STATUS_SHUTDOWN_IN_PROGRESS";
  case STATUS_SERVER_SHUTDOWN_IN_PROGRESS:                      return "STATUS_SERVER_SHUTDOWN_IN_PROGRESS";
  case STATUS_NOT_SUPPORTED_ON_SBS:                             return "STATUS_NOT_SUPPORTED_ON_SBS";
  case STATUS_WMI_GUID_DISCONNECTED:                            return "STATUS_WMI_GUID_DISCONNECTED";
  case STATUS_WMI_ALREADY_DISABLED:                             return "STATUS_WMI_ALREADY_DISABLED";
  case STATUS_WMI_ALREADY_ENABLED:                              return "STATUS_WMI_ALREADY_ENABLED";
  case STATUS_MFT_TOO_FRAGMENTED:                               return "STATUS_MFT_TOO_FRAGMENTED";
  case STATUS_COPY_PROTECTION_FAILURE:                          return "STATUS_COPY_PROTECTION_FAILURE";
  case STATUS_CSS_AUTHENTICATION_FAILURE:                       return "STATUS_CSS_AUTHENTICATION_FAILURE";
  case STATUS_CSS_KEY_NOT_PRESENT:                              return "STATUS_CSS_KEY_NOT_PRESENT";
  case STATUS_CSS_KEY_NOT_ESTABLISHED:                          return "STATUS_CSS_KEY_NOT_ESTABLISHED";
  case STATUS_CSS_SCRAMBLED_SECTOR:                             return "STATUS_CSS_SCRAMBLED_SECTOR";
  case STATUS_CSS_REGION_MISMATCH:                              return "STATUS_CSS_REGION_MISMATCH";
  case STATUS_CSS_RESETS_EXHAUSTED:                             return "STATUS_CSS_RESETS_EXHAUSTED";
  case STATUS_PKINIT_FAILURE:                                   return "STATUS_PKINIT_FAILURE";
  case STATUS_SMARTCARD_SUBSYSTEM_FAILURE:                      return "STATUS_SMARTCARD_SUBSYSTEM_FAILURE";
  case STATUS_NO_KERB_KEY:                                      return "STATUS_NO_KERB_KEY";
  case STATUS_HOST_DOWN:                                        return "STATUS_HOST_DOWN";
  case STATUS_UNSUPPORTED_PREAUTH:                              return "STATUS_UNSUPPORTED_PREAUTH";
  case STATUS_EFS_ALG_BLOB_TOO_BIG:                             return "STATUS_EFS_ALG_BLOB_TOO_BIG";
  case STATUS_PORT_NOT_SET:                                     return "STATUS_PORT_NOT_SET";
  case STATUS_DEBUGGER_INACTIVE:                                return "STATUS_DEBUGGER_INACTIVE";
  case STATUS_DS_VERSION_CHECK_FAILURE:                         return "STATUS_DS_VERSION_CHECK_FAILURE";
  case STATUS_AUDITING_DISABLED:                                return "STATUS_AUDITING_DISABLED";
  case STATUS_PRENT4_MACHINE_ACCOUNT:                           return "STATUS_PRENT4_MACHINE_ACCOUNT";
  case STATUS_DS_AG_CANT_HAVE_UNIVERSAL_MEMBER:                 return "STATUS_DS_AG_CANT_HAVE_UNIVERSAL_MEMBER";
  case STATUS_INVALID_IMAGE_WIN_32:                             return "STATUS_INVALID_IMAGE_WIN_32";
  case STATUS_INVALID_IMAGE_WIN_64:                             return "STATUS_INVALID_IMAGE_WIN_64";
  case STATUS_BAD_BINDINGS:                                     return "STATUS_BAD_BINDINGS";
  case STATUS_NETWORK_SESSION_EXPIRED:                          return "STATUS_NETWORK_SESSION_EXPIRED";
  case STATUS_APPHELP_BLOCK:                                    return "STATUS_APPHELP_BLOCK";
  case STATUS_ALL_SIDS_FILTERED:                                return "STATUS_ALL_SIDS_FILTERED";
  case STATUS_NOT_SAFE_MODE_DRIVER:                             return "STATUS_NOT_SAFE_MODE_DRIVER";
  case STATUS_ACCESS_DISABLED_BY_POLICY_DEFAULT:                return "STATUS_ACCESS_DISABLED_BY_POLICY_DEFAULT";
  case STATUS_ACCESS_DISABLED_BY_POLICY_PATH:                   return "STATUS_ACCESS_DISABLED_BY_POLICY_PATH";
  case STATUS_ACCESS_DISABLED_BY_POLICY_PUBLISHER:              return "STATUS_ACCESS_DISABLED_BY_POLICY_PUBLISHER";
  case STATUS_ACCESS_DISABLED_BY_POLICY_OTHER:                  return "STATUS_ACCESS_DISABLED_BY_POLICY_OTHER";
  case STATUS_FAILED_DRIVER_ENTRY:                              return "STATUS_FAILED_DRIVER_ENTRY";
  case STATUS_DEVICE_ENUMERATION_ERROR:                         return "STATUS_DEVICE_ENUMERATION_ERROR";
  case STATUS_WAIT_FOR_OPLOCK:                                  return "STATUS_WAIT_FOR_OPLOCK";
  case STATUS_MOUNT_POINT_NOT_RESOLVED:                         return "STATUS_MOUNT_POINT_NOT_RESOLVED";
  case STATUS_INVALID_DEVICE_OBJECT_PARAMETER:                  return "STATUS_INVALID_DEVICE_OBJECT_PARAMETER";
  case STATUS_MCA_OCCURED:                                      return "STATUS_MCA_OCCURED";
  case STATUS_DRIVER_BLOCKED_CRITICAL:                          return "STATUS_DRIVER_BLOCKED_CRITICAL";
  case STATUS_DRIVER_BLOCKED:                                   return "STATUS_DRIVER_BLOCKED";
  case STATUS_DRIVER_DATABASE_ERROR:                            return "STATUS_DRIVER_DATABASE_ERROR";
  case STATUS_SYSTEM_HIVE_TOO_LARGE:                            return "STATUS_SYSTEM_HIVE_TOO_LARGE";
  case STATUS_INVALID_IMPORT_OF_NON_DLL:                        return "STATUS_INVALID_IMPORT_OF_NON_DLL";
  case STATUS_DS_SHUTTING_DOWN:                                 return "STATUS_DS_SHUTTING_DOWN";
  case STATUS_SMARTCARD_WRONG_PIN:                              return "STATUS_SMARTCARD_WRONG_PIN";
  case STATUS_SMARTCARD_CARD_BLOCKED:                           return "STATUS_SMARTCARD_CARD_BLOCKED";
  case STATUS_SMARTCARD_CARD_NOT_AUTHENTICATED:                 return "STATUS_SMARTCARD_CARD_NOT_AUTHENTICATED";
  case STATUS_SMARTCARD_NO_CARD:                                return "STATUS_SMARTCARD_NO_CARD";
  case STATUS_SMARTCARD_NO_KEY_CONTAINER:                       return "STATUS_SMARTCARD_NO_KEY_CONTAINER";
  case STATUS_SMARTCARD_NO_CERTIFICATE:                         return "STATUS_SMARTCARD_NO_CERTIFICATE";
  case STATUS_SMARTCARD_NO_KEYSET:                              return "STATUS_SMARTCARD_NO_KEYSET";
  case STATUS_SMARTCARD_IO_ERROR:                               return "STATUS_SMARTCARD_IO_ERROR";
  case STATUS_DOWNGRADE_DETECTED:                               return "STATUS_DOWNGRADE_DETECTED";
  case STATUS_SMARTCARD_CERT_REVOKED:                           return "STATUS_SMARTCARD_CERT_REVOKED";
  case STATUS_ISSUING_CA_UNTRUSTED:                             return "STATUS_ISSUING_CA_UNTRUSTED";
  case STATUS_REVOCATION_OFFLINE_C:                             return "STATUS_REVOCATION_OFFLINE_C";
  case STATUS_PKINIT_CLIENT_FAILURE:                            return "STATUS_PKINIT_CLIENT_FAILURE";
  case STATUS_SMARTCARD_CERT_EXPIRED:                           return "STATUS_SMARTCARD_CERT_EXPIRED";
  case STATUS_DRIVER_FAILED_PRIOR_UNLOAD:                       return "STATUS_DRIVER_FAILED_PRIOR_UNLOAD";
  case STATUS_WOW_ASSERTION:                                    return "STATUS_WOW_ASSERTION";
  case STATUS_ACPI_INVALID_OPCODE:                              return "STATUS_ACPI_INVALID_OPCODE";
  case STATUS_ACPI_STACK_OVERFLOW:                              return "STATUS_ACPI_STACK_OVERFLOW";
  case STATUS_ACPI_ASSERT_FAILED:                               return "STATUS_ACPI_ASSERT_FAILED";
  case STATUS_ACPI_INVALID_INDEX:                               return "STATUS_ACPI_INVALID_INDEX";
  case STATUS_ACPI_INVALID_ARGUMENT:                            return "STATUS_ACPI_INVALID_ARGUMENT";
  case STATUS_ACPI_FATAL:                                       return "STATUS_ACPI_FATAL";
  case STATUS_ACPI_INVALID_SUPERNAME:                           return "STATUS_ACPI_INVALID_SUPERNAME";
  case STATUS_ACPI_INVALID_ARGTYPE:                             return "STATUS_ACPI_INVALID_ARGTYPE";
  case STATUS_ACPI_INVALID_OBJTYPE:                             return "STATUS_ACPI_INVALID_OBJTYPE";
  case STATUS_ACPI_INVALID_TARGETTYPE:                          return "STATUS_ACPI_INVALID_TARGETTYPE";
  case STATUS_ACPI_INCORRECT_ARGUMENT_COUNT:                    return "STATUS_ACPI_INCORRECT_ARGUMENT_COUNT";
  case STATUS_ACPI_ADDRESS_NOT_MAPPED:                          return "STATUS_ACPI_ADDRESS_NOT_MAPPED";
  case STATUS_ACPI_INVALID_EVENTTYPE:                           return "STATUS_ACPI_INVALID_EVENTTYPE";
  case STATUS_ACPI_HANDLER_COLLISION:                           return "STATUS_ACPI_HANDLER_COLLISION";
  case STATUS_ACPI_INVALID_DATA:                                return "STATUS_ACPI_INVALID_DATA";
  case STATUS_ACPI_INVALID_REGION:                              return "STATUS_ACPI_INVALID_REGION";
  case STATUS_ACPI_INVALID_ACCESS_SIZE:                         return "STATUS_ACPI_INVALID_ACCESS_SIZE";
  case STATUS_ACPI_ACQUIRE_GLOBAL_LOCK:                         return "STATUS_ACPI_ACQUIRE_GLOBAL_LOCK";
  case STATUS_ACPI_ALREADY_INITIALIZED:                         return "STATUS_ACPI_ALREADY_INITIALIZED";
  case STATUS_ACPI_NOT_INITIALIZED:                             return "STATUS_ACPI_NOT_INITIALIZED";
  case STATUS_ACPI_INVALID_MUTEX_LEVEL:                         return "STATUS_ACPI_INVALID_MUTEX_LEVEL";
  case STATUS_ACPI_MUTEX_NOT_OWNED:                             return "STATUS_ACPI_MUTEX_NOT_OWNED";
  case STATUS_ACPI_MUTEX_NOT_OWNER:                             return "STATUS_ACPI_MUTEX_NOT_OWNER";
  case STATUS_ACPI_RS_ACCESS:                                   return "STATUS_ACPI_RS_ACCESS";
  case STATUS_ACPI_INVALID_TABLE:                               return "STATUS_ACPI_INVALID_TABLE";
  case STATUS_ACPI_REG_HANDLER_FAILED:                          return "STATUS_ACPI_REG_HANDLER_FAILED";
  case STATUS_ACPI_POWER_REQUEST_FAILED:                        return "STATUS_ACPI_POWER_REQUEST_FAILED";
  case STATUS_CTX_WINSTATION_NAME_INVALID:                      return "STATUS_CTX_WINSTATION_NAME_INVALID";
  case STATUS_CTX_INVALID_PD:                                   return "STATUS_CTX_INVALID_PD";
  case STATUS_CTX_PD_NOT_FOUND:                                 return "STATUS_CTX_PD_NOT_FOUND";
  case STATUS_CTX_CDM_CONNECT:                                  return "STATUS_CTX_CDM_CONNECT";
  case STATUS_CTX_CDM_DISCONNECT:                               return "STATUS_CTX_CDM_DISCONNECT";
  case STATUS_CTX_CLOSE_PENDING:                                return "STATUS_CTX_CLOSE_PENDING";
  case STATUS_CTX_NO_OUTBUF:                                    return "STATUS_CTX_NO_OUTBUF";
  case STATUS_CTX_MODEM_INF_NOT_FOUND:                          return "STATUS_CTX_MODEM_INF_NOT_FOUND";
  case STATUS_CTX_INVALID_MODEMNAME:                            return "STATUS_CTX_INVALID_MODEMNAME";
  case STATUS_CTX_RESPONSE_ERROR:                               return "STATUS_CTX_RESPONSE_ERROR";
  case STATUS_CTX_MODEM_RESPONSE_TIMEOUT:                       return "STATUS_CTX_MODEM_RESPONSE_TIMEOUT";
  case STATUS_CTX_MODEM_RESPONSE_NO_CARRIER:                    return "STATUS_CTX_MODEM_RESPONSE_NO_CARRIER";
  case STATUS_CTX_MODEM_RESPONSE_NO_DIALTONE:                   return "STATUS_CTX_MODEM_RESPONSE_NO_DIALTONE";
  case STATUS_CTX_MODEM_RESPONSE_BUSY:                          return "STATUS_CTX_MODEM_RESPONSE_BUSY";
  case STATUS_CTX_MODEM_RESPONSE_VOICE:                         return "STATUS_CTX_MODEM_RESPONSE_VOICE";
  case STATUS_CTX_TD_ERROR:                                     return "STATUS_CTX_TD_ERROR";
  case STATUS_CTX_LICENSE_CLIENT_INVALID:                       return "STATUS_CTX_LICENSE_CLIENT_INVALID";
  case STATUS_CTX_LICENSE_NOT_AVAILABLE:                        return "STATUS_CTX_LICENSE_NOT_AVAILABLE";
  case STATUS_CTX_LICENSE_EXPIRED:                              return "STATUS_CTX_LICENSE_EXPIRED";
  case STATUS_CTX_WINSTATION_NOT_FOUND:                         return "STATUS_CTX_WINSTATION_NOT_FOUND";
  case STATUS_CTX_WINSTATION_NAME_COLLISION:                    return "STATUS_CTX_WINSTATION_NAME_COLLISION";
  case STATUS_CTX_WINSTATION_BUSY:                              return "STATUS_CTX_WINSTATION_BUSY";
  case STATUS_CTX_BAD_VIDEO_MODE:                               return "STATUS_CTX_BAD_VIDEO_MODE";
  case STATUS_CTX_GRAPHICS_INVALID:                             return "STATUS_CTX_GRAPHICS_INVALID";
  case STATUS_CTX_NOT_CONSOLE:                                  return "STATUS_CTX_NOT_CONSOLE";
  case STATUS_CTX_CLIENT_QUERY_TIMEOUT:                         return "STATUS_CTX_CLIENT_QUERY_TIMEOUT";
  case STATUS_CTX_CONSOLE_DISCONNECT:                           return "STATUS_CTX_CONSOLE_DISCONNECT";
  case STATUS_CTX_CONSOLE_CONNECT:                              return "STATUS_CTX_CONSOLE_CONNECT";
  case STATUS_CTX_SHADOW_DENIED:                                return "STATUS_CTX_SHADOW_DENIED";
  case STATUS_CTX_WINSTATION_ACCESS_DENIED:                     return "STATUS_CTX_WINSTATION_ACCESS_DENIED";
  case STATUS_CTX_INVALID_WD:                                   return "STATUS_CTX_INVALID_WD";
  case STATUS_CTX_WD_NOT_FOUND:                                 return "STATUS_CTX_WD_NOT_FOUND";
  case STATUS_CTX_SHADOW_INVALID:                               return "STATUS_CTX_SHADOW_INVALID";
  case STATUS_CTX_SHADOW_DISABLED:                              return "STATUS_CTX_SHADOW_DISABLED";
  case STATUS_RDP_PROTOCOL_ERROR:                               return "STATUS_RDP_PROTOCOL_ERROR";
  case STATUS_CTX_CLIENT_LICENSE_NOT_SET:                       return "STATUS_CTX_CLIENT_LICENSE_NOT_SET";
  case STATUS_CTX_CLIENT_LICENSE_IN_USE:                        return "STATUS_CTX_CLIENT_LICENSE_IN_USE";
  case STATUS_CTX_SHADOW_ENDED_BY_MODE_CHANGE:                  return "STATUS_CTX_SHADOW_ENDED_BY_MODE_CHANGE";
  case STATUS_CTX_SHADOW_NOT_RUNNING:                           return "STATUS_CTX_SHADOW_NOT_RUNNING";
  case STATUS_PNP_BAD_MPS_TABLE:                                return "STATUS_PNP_BAD_MPS_TABLE";
  case STATUS_PNP_TRANSLATION_FAILED:                           return "STATUS_PNP_TRANSLATION_FAILED";
  case STATUS_PNP_IRQ_TRANSLATION_FAILED:                       return "STATUS_PNP_IRQ_TRANSLATION_FAILED";
  case STATUS_SXS_SECTION_NOT_FOUND:                            return "STATUS_SXS_SECTION_NOT_FOUND";
  case STATUS_SXS_CANT_GEN_ACTCTX:                              return "STATUS_SXS_CANT_GEN_ACTCTX";
  case STATUS_SXS_INVALID_ACTCTXDATA_FORMAT:                    return "STATUS_SXS_INVALID_ACTCTXDATA_FORMAT";
  case STATUS_SXS_ASSEMBLY_NOT_FOUND:                           return "STATUS_SXS_ASSEMBLY_NOT_FOUND";
  case STATUS_SXS_MANIFEST_FORMAT_ERROR:                        return "STATUS_SXS_MANIFEST_FORMAT_ERROR";
  case STATUS_SXS_MANIFEST_PARSE_ERROR:                         return "STATUS_SXS_MANIFEST_PARSE_ERROR";
  case STATUS_SXS_ACTIVATION_CONTEXT_DISABLED:                  return "STATUS_SXS_ACTIVATION_CONTEXT_DISABLED";
  case STATUS_SXS_KEY_NOT_FOUND:                                return "STATUS_SXS_KEY_NOT_FOUND";
  case STATUS_SXS_VERSION_CONFLICT:                             return "STATUS_SXS_VERSION_CONFLICT";
  case STATUS_SXS_WRONG_SECTION_TYPE:                           return "STATUS_SXS_WRONG_SECTION_TYPE";
  case STATUS_SXS_THREAD_QUERIES_DISABLED:                      return "STATUS_SXS_THREAD_QUERIES_DISABLED";
  case STATUS_SXS_ASSEMBLY_MISSING:                             return "STATUS_SXS_ASSEMBLY_MISSING";
  case STATUS_SXS_RELEASE_ACTIVATION_CONTEXT:                   return "STATUS_SXS_RELEASE_ACTIVATION_CONTEXT";
  case STATUS_SXS_PROCESS_DEFAULT_ALREADY_SET:                  return "STATUS_SXS_PROCESS_DEFAULT_ALREADY_SET";
  case STATUS_SXS_EARLY_DEACTIVATION:                           return "STATUS_SXS_EARLY_DEACTIVATION";
  case STATUS_SXS_INVALID_DEACTIVATION:                         return "STATUS_SXS_INVALID_DEACTIVATION";
  case STATUS_SXS_MULTIPLE_DEACTIVATION:                        return "STATUS_SXS_MULTIPLE_DEACTIVATION";
  case STATUS_SXS_SYSTEM_DEFAULT_ACTIVATION_CONTEXT_EMPTY:      return "STATUS_SXS_SYSTEM_DEFAULT_ACTIVATION_CONTEXT_EMPTY";
  case STATUS_SXS_PROCESS_TERMINATION_REQUESTED:                return "STATUS_SXS_PROCESS_TERMINATION_REQUESTED";
  case STATUS_CLUSTER_INVALID_NODE:                             return "STATUS_CLUSTER_INVALID_NODE";
  case STATUS_CLUSTER_NODE_EXISTS:                              return "STATUS_CLUSTER_NODE_EXISTS";
  case STATUS_CLUSTER_JOIN_IN_PROGRESS:                         return "STATUS_CLUSTER_JOIN_IN_PROGRESS";
  case STATUS_CLUSTER_NODE_NOT_FOUND:                           return "STATUS_CLUSTER_NODE_NOT_FOUND";
  case STATUS_CLUSTER_LOCAL_NODE_NOT_FOUND:                     return "STATUS_CLUSTER_LOCAL_NODE_NOT_FOUND";
  case STATUS_CLUSTER_NETWORK_EXISTS:                           return "STATUS_CLUSTER_NETWORK_EXISTS";
  case STATUS_CLUSTER_NETWORK_NOT_FOUND:                        return "STATUS_CLUSTER_NETWORK_NOT_FOUND";
  case STATUS_CLUSTER_NETINTERFACE_EXISTS:                      return "STATUS_CLUSTER_NETINTERFACE_EXISTS";
  case STATUS_CLUSTER_NETINTERFACE_NOT_FOUND:                   return "STATUS_CLUSTER_NETINTERFACE_NOT_FOUND";
  case STATUS_CLUSTER_INVALID_REQUEST:                          return "STATUS_CLUSTER_INVALID_REQUEST";
  case STATUS_CLUSTER_INVALID_NETWORK_PROVIDER:                 return "STATUS_CLUSTER_INVALID_NETWORK_PROVIDER";
  case STATUS_CLUSTER_NODE_DOWN:                                return "STATUS_CLUSTER_NODE_DOWN";
  case STATUS_CLUSTER_NODE_UNREACHABLE:                         return "STATUS_CLUSTER_NODE_UNREACHABLE";
  case STATUS_CLUSTER_NODE_NOT_MEMBER:                          return "STATUS_CLUSTER_NODE_NOT_MEMBER";
  case STATUS_CLUSTER_JOIN_NOT_IN_PROGRESS:                     return "STATUS_CLUSTER_JOIN_NOT_IN_PROGRESS";
  case STATUS_CLUSTER_INVALID_NETWORK:                          return "STATUS_CLUSTER_INVALID_NETWORK";
  case STATUS_CLUSTER_NO_NET_ADAPTERS:                          return "STATUS_CLUSTER_NO_NET_ADAPTERS";
  case STATUS_CLUSTER_NODE_UP:                                  return "STATUS_CLUSTER_NODE_UP";
  case STATUS_CLUSTER_NODE_PAUSED:                              return "STATUS_CLUSTER_NODE_PAUSED";
  case STATUS_CLUSTER_NODE_NOT_PAUSED:                          return "STATUS_CLUSTER_NODE_NOT_PAUSED";
  case STATUS_CLUSTER_NO_SECURITY_CONTEXT:                      return "STATUS_CLUSTER_NO_SECURITY_CONTEXT";
  case STATUS_CLUSTER_NETWORK_NOT_INTERNAL:                     return "STATUS_CLUSTER_NETWORK_NOT_INTERNAL";
  case STATUS_CLUSTER_POISONED:                                 return "STATUS_CLUSTER_POISONED";
  }

  return "UNKNOWN STATUS";
}

#if defined(MRB_UTF8_STRING)
# define DEFAULT_CODEPAGE CP_UTF8
#else
# define DEFAULT_CODEPAGE CP_OEMCP
#endif

static inline mrb_bool
is_drive_letter_only(const char path[])
{
  if ((size_t)((path[0] | 0x40) - 'a') <= ('z' - 'a') && path[1] == ':' && path[2] == '\0') {
    return TRUE;
  } else {
    return FALSE;
  }
}

// https://learn.microsoft.com/ja-jp/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ntopenfile
// https://learn.microsoft.com/ja-jp/windows-hardware/drivers/ddi/ntifs/nf-ntifs-zwopendirectoryobject
// https://learn.microsoft.com/ja-jp/windows/win32/api/ntdef/nf-ntdef-initializeobjectattributes
// https://learn.microsoft.com/ja-jp/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ntquerydirectoryfile
// https://learn.microsoft.com/ja-jp/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ntquerydirectoryfileex
// https://learn.microsoft.com/ja-jp/windows-hardware/drivers/ddi/ntifs/ns-ntifs-_file_names_information
// https://learn.microsoft.com/ja-jp/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ntclose
// https://learn.microsoft.com/ja-jp/windows/win32/debug/system-error-codes
// https://learn.microsoft.com/ja-jp/windows/win32/api/stringapiset/nf-stringapiset-multibytetowidechar
// https://learn.microsoft.com/ja-jp/windows-hardware/drivers/ddi/ntifs/nf-ntifs-rtlallocateheap
// https://learn.microsoft.com/ja-jp/windows-hardware/drivers/ddi/ntifs/nf-ntifs-rtlfreeheap
//
// https://source.winehq.org/git/wine.git/blob/d2c11cdd945a438ccaf86658a6fb62a0a419414f:/dlls/kernelbase/file.c#l1154
// https://github.com/wine-mirror/wine/blob/d2c11cdd945a438ccaf86658a6fb62a0a419414f/dlls/kernelbase/file.c#L1154

/*
 *  NtOpenFile() を呼び出してファイルハンドルを返す。
 */
static inline HANDLE
aux_file_open(const char path[], UINT codepage, uint32_t options)
{
  if (!path || path[0] == '\0') {
    errno = EINVAL;
    return NULL;
  }

  int wlen = 0;
  wchar_t *wpath = NULL;
  for (;;) {
    wlen = MultiByteToWideChar(codepage, 0, path, -1, wpath, wlen);
    if (wlen < 1) {
      errno = EINVAL;
      RtlFreeHeap(GetProcessHeap(), 0, wpath);
      return NULL;
    } else if (wlen > INT16_MAX) {
      errno = ENAMETOOLONG;
      RtlFreeHeap(GetProcessHeap(), 0, wpath);
      return NULL;
    }

    if (wpath) {
      wpath[wlen] = L'\0';
      break;
    }

    wpath = (wchar_t *)RtlAllocateHeap(GetProcessHeap(), 0, (wlen + 1) * sizeof(wchar_t));
    if (!wpath) {
      errno = ENOMEM;
      return NULL;
    }
  }

  UNICODE_STRING name = { 0, 0, NULL };
  BOOLEAN success = RtlDosPathNameToNtPathName_U(wpath, &name, NULL, NULL);
  RtlFreeHeap(GetProcessHeap(), 0, wpath);
  if (!success) {
    errno = ENOENT;
    return NULL;
  }

  OBJECT_ATTRIBUTES attr;
  InitializeObjectAttributes(&attr, &name, OBJ_CASE_INSENSITIVE, NULL, NULL);

  HANDLE file;
  IO_STATUS_BLOCK io;
  NTSTATUS ntst = NtOpenFile(&file, GENERIC_READ | SYNCHRONIZE, &attr, &io,
                             FILE_SHARE_READ | FILE_SHARE_WRITE, options);
  RtlFreeUnicodeString(&name);
  if (IS_ERROR(ntst)) {
    errno = ntstatus_to_errno(ntst);
    return NULL;
  }

  return file;
}

typedef struct mruby_find_dir DIR;

struct dirent
{
  //uint8_t  d_type; // WIN32_FIND_DATA::dwFileAttributes からの変換値
  uint16_t d_namlen;
  char d_name[1024]; // 現在のコードページに基づく多バイト長文字列、あるいは UTF-8 文字列
};

struct mruby_find_dir
{
  HANDLE dirfile;
  enum { find_state_init, find_state_iter, find_state_term } state;
  struct dirent dirent;
};

static struct mruby_find_dir *
mruby_find_opendir(mrb_state *mrb, const char *filename)
{
  struct mruby_find_dir *dir = (struct mruby_find_dir *)mrb_malloc_simple(mrb, sizeof(struct mruby_find_dir));
  if (!dir) {
    errno = ENOMEM;
    return NULL;
  }

  dir->dirfile = aux_file_open(filename, DEFAULT_CODEPAGE,
                               FILE_DIRECTORY_FILE | FILE_SYNCHRONOUS_IO_NONALERT | FILE_OPEN_FOR_BACKUP_INTENT);
  if (!dir->dirfile) {
    mrb_free(mrb, dir);
    return NULL;
  }

  return dir;
}

static int
mruby_find_closedir(mrb_state *mrb, struct mruby_find_dir *dir)
{
  NTSTATUS ntst = NtClose(dir->dirfile);
  mrb_free(mrb, dir);
  if (IS_ERROR(ntst)) {
    errno = ntstatus_to_errno(ntst);
    return -1;
  } else {
    return 0;
  }
}

static struct dirent *
mruby_find_readdir(mrb_state *mrb, struct mruby_find_dir *dir)
{
  if (dir->state == find_state_term) {
    errno = 0;
    return NULL;
  }

  IO_STATUS_BLOCK iostatus;
  union { char beta[1024]; FILE_NAMES_INFORMATION nameinfo; } aa;
  NTSTATUS ntst = NtQueryDirectoryFile(dir->dirfile, NULL, NULL, NULL,
                                       &iostatus, &aa, sizeof(aa), FileNamesInformation,
                                       TRUE, NULL, (dir->state == find_state_init ? TRUE : FALSE));
  if (IS_ERROR(ntst)) {
    dir->state = find_state_term;
    if (ntst != STATUS_NO_MORE_FILES) {
      errno = ntstatus_to_errno(ntst);
    }
    return NULL;
  }

  int len = WideCharToMultiByte(DEFAULT_CODEPAGE, 0,
                                aa.nameinfo.FileName, aa.nameinfo.FileNameLength / sizeof(WCHAR),
                                dir->dirent.d_name, sizeof(dir->dirent.d_name), NULL, NULL);
  if (len < 1 || len > INT16_MAX) {
    dir->state = find_state_term;
    errno = ENAMETOOLONG;
    return NULL;
  }

  dir->state = find_state_iter;
  dir->dirent.d_namlen = len;

  return &dir->dirent;
}

#define opendir(path)   mruby_find_opendir(mrb, path)
#define closedir(dir)   mruby_find_closedir(mrb, dir)
#define readdir(path)   mruby_find_readdir(mrb, path)

static mrb_value
prepare_prefix_win32(mrb_state *mrb, const char path[], mrb_value prefix)
{
  char *p = RSTRING_PTR(prefix);
  size_t ps = RSTRING_LEN(prefix);
  int32_t lastch = -1;

# ifdef MRB_UTF8_STRING
  for (; ps > 0; ps--, p++) {
    lastch = (uint8_t)*p;
  }
# else
  TODO("mbrlen() ではなくてコードページを用いたものに置き換えたい")

  union { char zero[sizeof(mbstate_t)]; mbstate_t mbs; } u = { { 0 } };
  while (ps > 0) {
    int s = mbrlen(p, ps, &u.mbs);
    if (s == 1) {
      lastch = (uint8_t)*p;
    } else if (s < 1) {
      s = 1;
      lastch = -1;
    } else {
      lastch = -1;
    }

    p += s;
    ps -= s;
  }
# endif // MRB_UTF8_STRING

  if (!is_drive_letter_only(path) && lastch != '/' && lastch != '\\') {
    mrb_str_cat_cstr(mrb, prefix, "/");
  }

  return prefix;
}

static mrb_value
file_directory_p_win32(mrb_state *mrb, const char path[], mrb_bool ignore_err)
{
  //
  //  references:
  //    https://learn.microsoft.com/ja-jp/windows/win32/fileio/symbolic-link-effects-on-file-systems-functions
  //    https://learn.microsoft.com/ja-jp/windows/win32/api/fileapi/nf-fileapi-getfileattributesa
  //    https://learn.microsoft.com/ja-jp/windows/win32/fileio/file-attribute-constants
  //    https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ntqueryinformationfile
  //    https://emk.name/symlink.html
  //

  HANDLE file = aux_file_open(path, DEFAULT_CODEPAGE, FILE_OPEN_REPARSE_POINT);
  if (!file) {
    return dir_error(mrb, path, ignore_err);
  }

  IO_STATUS_BLOCK iostatus;
  FILE_ATTRIBUTE_TAG_INFORMATION attr;
  NTSTATUS ntst = NtQueryInformationFile(file, &iostatus, &attr, sizeof(attr), FileAttributeTagInformation);
  NtClose(file);
  if (IS_ERROR(ntst)) {
    errno = ntstatus_to_errno(ntst);
    return dir_error(mrb, path, ignore_err);
  }

  if (!(attr.FileAttributes & FILE_ATTRIBUTE_DIRECTORY)) {
    return mrb_false_value();
  }

  TODO("この部分の検証が必要")
  if ((attr.FileAttributes & FILE_ATTRIBUTE_REPARSE_POINT) &&
      IsReparseTagValid(attr.ReparseTag) &&
      (attr.ReparseTag & IO_REPARSE_TAG_VALID_VALUES) == IO_REPARSE_TAG_SYMLINK) {
    return mrb_false_value();
  }

  return mrb_true_value();
}

// vim: set filetype=c syntax=c :
